// SAT Prep — starter question bank
// Each question: { id, subject: 'math'|'english', difficulty: 'easy'|'medium'|'hard',
//                   topic, question, choices: [4], answer: index, explanation }

const QUESTIONS = [
  // ---------------- MATH · EASY ----------------
  { id: 'm-e-1', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'If x + 8 = 20, what is the value of x?',
    choices: ['10', '12', '14', '28'], answer: 1,
    explanation: 'Subtract 8 from both sides: x = 20 - 8 = 12.' },
  { id: 'm-e-2', subject: 'math', difficulty: 'easy', topic: 'Percentages', noCalcEligible: true,
    question: 'What is 15% of 200?',
    choices: ['20', '25', '30', '35'], answer: 2,
    explanation: '15% of 200 = 0.15 × 200 = 30.' },
  { id: 'm-e-3', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'Solve for x: 3x - 5 = 16',
    choices: ['5', '6', '7', '8'], answer: 2,
    explanation: 'Add 5 to both sides: 3x = 21. Divide by 3: x = 7.' },
  { id: 'm-e-4', subject: 'math', difficulty: 'easy', topic: 'Ratios', noCalcEligible: true,
    question: 'A recipe calls for 2 cups of flour for every 3 cups of sugar. If you use 6 cups of sugar, how many cups of flour do you need?',
    choices: ['3', '4', '5', '6'], answer: 1,
    explanation: 'The ratio 2:3 scales to 4:6, so 4 cups of flour are needed.' },
  { id: 'm-e-5', subject: 'math', difficulty: 'easy', topic: 'Arithmetic', noCalcEligible: true,
    question: 'What is the average (arithmetic mean) of 4, 8, and 12?',
    choices: ['6', '7', '8', '9'], answer: 2,
    explanation: 'Sum = 24, divided by 3 values = 8.' },
  { id: 'm-e-6', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'If 5y = 45, what is the value of y?',
    choices: ['7', '8', '9', '10'], answer: 2,
    explanation: 'Divide both sides by 5: y = 45 / 5 = 9.' },
  { id: 'm-e-7', subject: 'math', difficulty: 'easy', topic: 'Percentages', noCalcEligible: true,
    question: 'A shirt originally costs $40. After a 25% discount, what is the sale price?',
    choices: ['$25', '$28', '$30', '$32'], answer: 2,
    explanation: '25% of $40 is $10. $40 - $10 = $30.' },
  { id: 'm-e-8', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'Solve for x: x / 4 = 9',
    choices: ['13', '24', '36', '40'], answer: 2,
    explanation: 'Multiply both sides by 4: x = 9 × 4 = 36.' },
  { id: 'm-e-9', subject: 'math', difficulty: 'easy', topic: 'Fractions and Decimals', noCalcEligible: true,
    question: 'What is 3/4 expressed as a decimal?',
    choices: ['0.34', '0.75', '1.34', '0.43'], answer: 1,
    explanation: '3 divided by 4 equals 0.75.' },
  { id: 'm-e-10', subject: 'math', difficulty: 'easy', topic: 'Geometry', noCalcEligible: true,
    question: 'If a triangle has sides of length 5, 12, and 13, what is its perimeter?',
    choices: ['25', '28', '30', '32'], answer: 2,
    explanation: 'Perimeter = 5 + 12 + 13 = 30.' },
  { id: 'm-e-11', subject: 'math', difficulty: 'easy', topic: 'Inequalities', noCalcEligible: true,
    question: 'Which value of x satisfies 2x + 3 < 11?',
    choices: ['3', '4', '5', '6'], answer: 0,
    explanation: '2x + 3 < 11 → 2x < 8 → x < 4. Only 3 is less than 4.' },
  { id: 'm-e-12', subject: 'math', difficulty: 'easy', topic: 'Arithmetic',
    question: 'A store sells notebooks for $2.50 each. How much do 6 notebooks cost?',
    choices: ['$12', '$13.50', '$15', '$17.50'], answer: 2,
    explanation: '6 × $2.50 = $15.' },
  { id: 'm-e-13', subject: 'math', difficulty: 'easy', topic: 'Exponents', noCalcEligible: true,
    question: 'What is the value of 4² - 3²?',
    choices: ['1', '5', '7', '9'], answer: 2,
    explanation: '16 - 9 = 7.' },
  { id: 'm-e-14', subject: 'math', difficulty: 'easy', topic: 'Rates',
    question: 'If a car travels at a constant speed of 50 miles per hour, how far does it travel in 2.5 hours?',
    choices: ['100', '110', '125', '150'], answer: 2,
    explanation: '50 × 2.5 = 125 miles.' },
  { id: 'm-e-15', subject: 'math', difficulty: 'easy', topic: 'Unit Conversion', noCalcEligible: true,
    question: 'Convert 3 feet 6 inches to inches.',
    choices: ['36', '40', '42', '48'], answer: 2,
    explanation: '3 feet = 36 inches. 36 + 6 = 42 inches.' },
  { id: 'm-e-16', subject: 'math', difficulty: 'easy', topic: 'Number Theory', noCalcEligible: true,
    question: 'What is the least common multiple of 4 and 6?',
    choices: ['8', '10', '12', '24'], answer: 2,
    explanation: 'Multiples of 4: 4, 8, 12... Multiples of 6: 6, 12... The smallest shared multiple is 12.' },
  { id: 'm-e-17', subject: 'math', difficulty: 'easy', topic: 'Probability', noCalcEligible: true,
    question: 'A jar contains 5 green and 5 yellow candies. What is the probability of picking a yellow candy at random?',
    choices: ['1/4', '1/3', '1/2', '2/3'], answer: 2,
    explanation: 'There are 5 yellow candies out of 10 total, so the probability is 5/10 = 1/2.' },
  { id: 'm-e-18', subject: 'math', difficulty: 'easy', topic: 'Order of Operations', noCalcEligible: true,
    question: 'Simplify: 6 + 2 × 3',
    choices: ['12', '18', '24', '8'], answer: 0,
    explanation: 'Multiplication before addition: 2 × 3 = 6, then 6 + 6 = 12.' },

  // ---------------- MATH · MEDIUM ----------------
  { id: 'm-m-1', subject: 'math', difficulty: 'medium', topic: 'Systems of Equations', noCalcEligible: true,
    question: 'If 2x + y = 11 and x - y = 1, what is the value of x?',
    choices: ['3', '4', '5', '6'], answer: 1,
    explanation: 'From x - y = 1, y = x - 1. Substituting: 2x + (x - 1) = 11 → 3x = 12 → x = 4.' },
  { id: 'm-m-2', subject: 'math', difficulty: 'medium', topic: 'Quadratics', noCalcEligible: true,
    question: 'Which of the following is a solution to x² - 5x + 6 = 0?',
    choices: ['1', '2', '4', '6'], answer: 1,
    explanation: 'Factoring gives (x - 2)(x - 3) = 0, so x = 2 or x = 3. Only 2 appears among the choices.' },
  { id: 'm-m-3', subject: 'math', difficulty: 'medium', topic: 'Geometry', noCalcEligible: true,
    question: 'A rectangle has a length of 12 and a width of 7. What is its area?',
    choices: ['70', '77', '84', '91'], answer: 2,
    explanation: 'Area = length × width = 12 × 7 = 84.' },
  { id: 'm-m-4', subject: 'math', difficulty: 'medium', topic: 'Geometry', noCalcEligible: true,
    question: 'A circle has a radius of 5. What is its circumference in terms of π?',
    choices: ['5π', '10π', '15π', '25π'], answer: 1,
    explanation: 'Circumference = 2πr = 2π(5) = 10π.' },
  { id: 'm-m-5', subject: 'math', difficulty: 'medium', topic: 'Exponents', noCalcEligible: true,
    question: 'Simplify: (2³)(2⁴)',
    choices: ['64', '128', '256', '512'], answer: 1,
    explanation: 'Add exponents when multiplying same base: 2³⁺⁴ = 2⁷ = 128.' },
  { id: 'm-m-6', subject: 'math', difficulty: 'medium', topic: 'Rates',
    question: 'A car travels 180 miles in 3 hours. At this rate, how many miles will it travel in 5 hours?',
    choices: ['270', '290', '300', '320'], answer: 2,
    explanation: 'Rate = 180 / 3 = 60 mph. In 5 hours: 60 × 5 = 300 miles.' },
  { id: 'm-m-7', subject: 'math', difficulty: 'medium', topic: 'Geometry',
    question: 'A rectangular box has dimensions 4 by 5 by 6. What is its volume?',
    choices: ['100', '110', '120', '130'], answer: 2,
    explanation: 'Volume = 4 × 5 × 6 = 120.' },
  { id: 'm-m-8', subject: 'math', difficulty: 'medium', topic: 'Systems of Equations',
    question: 'Tickets to a show cost $8 for adults and $5 for children. If 10 tickets were sold for a total of $65, how many child tickets were sold?',
    choices: ['3', '4', '5', '6'], answer: 2,
    explanation: 'Let a + c = 10 and 8a + 5c = 65. Substituting a = 10 - c gives 80 - 8c + 5c = 65 → -3c = -15 → c = 5.' },
  { id: 'm-m-9', subject: 'math', difficulty: 'medium', topic: 'Direct Variation', noCalcEligible: true,
    question: 'If y varies directly with x, and y = 20 when x = 4, what is y when x = 9?',
    choices: ['36', '40', '45', '49'], answer: 2,
    explanation: 'y = kx, so 20 = k(4) → k = 5. When x = 9, y = 5 × 9 = 45.' },
  { id: 'm-m-10', subject: 'math', difficulty: 'medium', topic: 'Similar Triangles', noCalcEligible: true,
    question: 'Two triangles are similar with a scale factor of 3. If the smaller triangle has a side length of 4, what is the corresponding side length in the larger triangle?',
    choices: ['7', '9', '12', '15'], answer: 2,
    explanation: 'Similar triangles scale proportionally: 4 × 3 = 12.' },
  { id: 'm-m-11', subject: 'math', difficulty: 'medium', topic: 'Simple Interest',
    question: 'A bank account earns 5% simple interest per year. If $2000 is deposited, how much interest is earned after 3 years?',
    choices: ['$100', '$200', '$300', '$400'], answer: 2,
    explanation: 'Simple interest = principal × rate × time = 2000 × 0.05 × 3 = $300.' },
  { id: 'm-m-12', subject: 'math', difficulty: 'medium', topic: 'Statistics', noCalcEligible: true,
    question: 'The mean of five numbers is 20. If four of the numbers are 15, 18, 22, and 25, what is the fifth number?',
    choices: ['15', '18', '20', '22'], answer: 2,
    explanation: 'The five numbers must sum to 100. 15 + 18 + 22 + 25 = 80, so the fifth number is 100 - 80 = 20.' },
  { id: 'm-m-13', subject: 'math', difficulty: 'medium', topic: 'Absolute Value', noCalcEligible: true,
    question: 'Which value of x satisfies |x - 4| = 10?',
    choices: ['-6', '-4', '4', '6'], answer: 0,
    explanation: 'x - 4 = -10 → x = -6 (or x - 4 = 10 → x = 14, not listed). Checking: |-6 - 4| = |-10| = 10. ✓' },
  { id: 'm-m-14', subject: 'math', difficulty: 'medium', topic: 'Polynomial Expansion', noCalcEligible: true,
    question: 'Which expression is equivalent to (x + 4)(x - 2)?',
    choices: ['x² + 2x - 8', 'x² - 2x + 8', 'x² + 6x - 8', 'x² - 6x - 8'], answer: 0,
    explanation: 'Using FOIL: x² - 2x + 4x - 8 = x² + 2x - 8.' },
  { id: 'm-m-15', subject: 'math', difficulty: 'medium', topic: 'Scale and Ratios',
    question: 'A map has a scale of 1 inch = 25 miles. If two cities are 4.5 inches apart on the map, what is the actual distance between them?',
    choices: ['100', '110', '112.5', '125'], answer: 2,
    explanation: '4.5 × 25 = 112.5 miles.' },
  { id: 'm-m-16', subject: 'math', difficulty: 'medium', topic: 'Angle Relationships', noCalcEligible: true,
    question: 'Two angles are supplementary. If one angle measures 65°, what is the measure of the other angle?',
    choices: ['105°', '115°', '125°', '135°'], answer: 1,
    explanation: 'Supplementary angles sum to 180°. 180 - 65 = 115.' },
  { id: 'm-m-17', subject: 'math', difficulty: 'medium', topic: 'Ratios',
    question: 'A recipe requires 3/4 cup of sugar for 12 cookies. How much sugar is needed for 20 cookies, assuming a constant ratio?',
    choices: ['1', '1.1', '1.25', '1.5'], answer: 2,
    explanation: 'Sugar per cookie = (3/4) / 12. For 20 cookies: (3/4) × (20/12) = (3/4) × (5/3) = 15/12 = 1.25 cups.' },
  { id: 'm-m-18', subject: 'math', difficulty: 'medium', topic: 'Inverse Variation', noCalcEligible: true,
    question: 'If x varies inversely with y, and x = 8 when y = 3, what is x when y = 6?',
    choices: ['2', '4', '6', '8'], answer: 1,
    explanation: 'xy = k = 8 × 3 = 24. When y = 6, x = 24 / 6 = 4.' },

  // ---------------- MATH · HARD ----------------
  { id: 'm-h-1', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'Which value of x satisfies 2x² + 3x - 2 = 0?',
    choices: ['-2', '-1', '1', '2'], answer: 0,
    explanation: 'Using the quadratic formula: x = (-3 ± √(9+16))/4 = (-3 ± 5)/4, giving x = 0.5 or x = -2. Only -2 appears among the choices.' },
  { id: 'm-h-2', subject: 'math', difficulty: 'hard', topic: 'Functions', noCalcEligible: true,
    question: 'If f(x) = 2x² - 3x + 1 and g(x) = f(x) + 4x, what is g(-1)?',
    choices: ['-2', '0', '2', '4'], answer: 2,
    explanation: 'f(-1) = 2(1) - 3(-1) + 1 = 6. Then g(-1) = f(-1) + 4(-1) = 6 - 4 = 2.' },
  { id: 'm-h-3', subject: 'math', difficulty: 'hard', topic: 'Exponential Growth',
    question: 'A population of bacteria doubles every 3 hours. If the initial population is 100, what is the population after 9 hours?',
    choices: ['300', '400', '800', '1600'], answer: 2,
    explanation: '9 hours = 3 doubling periods. 100 × 2³ = 800.' },
  { id: 'm-h-4', subject: 'math', difficulty: 'hard', topic: 'Trigonometry', noCalcEligible: true,
    question: 'In a right triangle, one angle measures 30°, and the hypotenuse is 10. What is the length of the side opposite the 30° angle?',
    choices: ['3', '5', '5√3', '10'], answer: 1,
    explanation: 'Opposite = hypotenuse × sin(30°) = 10 × 0.5 = 5.' },
  { id: 'm-h-5', subject: 'math', difficulty: 'hard', topic: 'Rational Expressions', noCalcEligible: true,
    question: 'Simplify: (x² - 9) / (x - 3), for x ≠ 3',
    choices: ['x - 3', 'x + 3', 'x² - 3', 'x + 9'], answer: 1,
    explanation: 'x² - 9 factors as (x - 3)(x + 3). Dividing by (x - 3) leaves x + 3.' },
  { id: 'm-h-6', subject: 'math', difficulty: 'hard', topic: 'Work Rate',
    question: 'Pipe A can fill a tank in 4 hours, and pipe B can fill the same tank in 6 hours. Working together, how many hours will it take to fill the tank?',
    choices: ['2', '2.4', '3', '5'], answer: 1,
    explanation: 'Combined rate = 1/4 + 1/6 = 5/12 tank per hour. Time = 12/5 = 2.4 hours.' },
  { id: 'm-h-7', subject: 'math', difficulty: 'hard', topic: 'Absolute Value Inequalities', noCalcEligible: true,
    question: 'For how many integer values of x is |3x - 4| < 11 true?',
    choices: ['5', '6', '7', '8'], answer: 2,
    explanation: 'Rewrite as -11 < 3x - 4 < 11, so -7 < 3x < 15, giving -7/3 < x < 5. The integers in that range are -2, -1, 0, 1, 2, 3, 4 — 7 values.' },
  { id: 'm-h-8', subject: 'math', difficulty: 'hard', topic: 'Coordinate Geometry',
    question: 'What is the slope of the line passing through points (2, 3) and (6, 11)?',
    choices: ['1', '2', '3', '4'], answer: 1,
    explanation: 'Slope = (11 - 3) / (6 - 2) = 8 / 4 = 2.' },
  { id: 'm-h-9', subject: 'math', difficulty: 'hard', topic: 'Quadratic-Linear Systems', noCalcEligible: true,
    question: 'If y = 2x - 3 and y = x² - 4x + 5, what is one possible value of x?',
    choices: ['1', '2', '3', '5'], answer: 1,
    explanation: 'Setting the equations equal: 2x - 3 = x² - 4x + 5 → x² - 6x + 8 = 0 → (x - 2)(x - 4) = 0, so x = 2 or x = 4. Only 2 appears among the choices.' },
  { id: 'm-h-10', subject: 'math', difficulty: 'hard', topic: 'Circle Equations', noCalcEligible: true,
    question: 'A circle is defined by the equation (x - 3)² + (y + 2)² = 25. What is the radius of the circle?',
    choices: ['4', '5', '6', '25'], answer: 1,
    explanation: 'In the standard form (x - h)² + (y - k)² = r², r² = 25, so r = 5.' },
  { id: 'm-h-11', subject: 'math', difficulty: 'hard', topic: 'Remainder Theorem', noCalcEligible: true,
    question: 'When the polynomial x³ - 2x² + kx - 6 is divided by (x - 3), the remainder is 0. What is the value of k?',
    choices: ['-3', '-1', '1', '3'], answer: 1,
    explanation: 'By the remainder theorem, substituting x = 3 must give 0: 27 - 18 + 3k - 6 = 0 → 3 + 3k = 0 → k = -1.' },
  { id: 'm-h-12', subject: 'math', difficulty: 'hard', topic: 'Exponential Decay', noCalcEligible: true,
    question: 'A car depreciates in value by 12% each year. If it is initially worth $25,000, which expression represents its value after t years?',
    choices: ['25000(0.12)^t', '25000(0.88)^t', '25000(1.12)^t', '25000 - 0.12t'], answer: 1,
    explanation: 'Losing 12% each year means 88% of the value remains, so the value after t years is 25000 multiplied by 0.88 raised to the t.' },
  { id: 'm-h-13', subject: 'math', difficulty: 'hard', topic: 'Statistics', noCalcEligible: true,
    question: 'Data set A has a mean of 50 and a standard deviation of 5. Data set B has the same mean but a standard deviation of 10. Which statement must be true?',
    choices: ['Data set A has a wider range of values than data set B.', "Data set B's values are more spread out from the mean than data set A's.", 'Data sets A and B have identical distributions.', 'Data set B has a higher mean than data set A.'], answer: 1,
    explanation: 'A larger standard deviation means the values are, on average, farther from the mean — indicating greater spread, not a different mean or a guaranteed wider range.' },
  { id: 'm-h-14', subject: 'math', difficulty: 'hard', topic: 'Sequences', noCalcEligible: true,
    question: 'In a geometric sequence, the first term is 3 and the common ratio is 2. What is the 6th term?',
    choices: ['48', '64', '96', '192'], answer: 2,
    explanation: 'The nth term is 3 × 2^(n-1). The 6th term is 3 × 2⁵ = 3 × 32 = 96.' },
  { id: 'm-h-15', subject: 'math', difficulty: 'hard', topic: 'Rational Equations', noCalcEligible: true,
    question: 'What is the solution to the equation 3/(x - 2) = 6/(x + 1), given x ≠ 2 and x ≠ -1?',
    choices: ['3', '4', '5', '6'], answer: 2,
    explanation: 'Cross-multiplying: 3(x + 1) = 6(x - 2) → 3x + 3 = 6x - 12 → -3x = -15 → x = 5.' },
  { id: 'm-h-16', subject: 'math', difficulty: 'hard', topic: 'Probability',
    question: 'A bag contains 4 red marbles and 6 blue marbles. If two marbles are drawn without replacement, what is the probability that both are red?',
    choices: ['1/15', '2/15', '3/15', '4/15'], answer: 1,
    explanation: 'P(both red) = (4/10) × (3/9) = 12/90 = 2/15.' },
  { id: 'm-h-17', subject: 'math', difficulty: 'hard', topic: 'Function Transformations', noCalcEligible: true,
    question: 'The graph of f(x) = x² is shifted 3 units right and 2 units up to create g(x). Which equation represents g(x)?',
    choices: ['(x - 3)² + 2', '(x + 3)² + 2', '(x - 3)² - 2', '(x + 3)² - 2'], answer: 0,
    explanation: 'A shift right by 3 replaces x with (x - 3); a shift up by 2 adds 2 to the result: g(x) = (x - 3)² + 2.' },
  { id: 'm-h-18', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'If 4^(x+1) = 64, what is the value of x?',
    choices: ['1', '2', '3', '4'], answer: 1,
    explanation: '64 = 4³, so x + 1 = 3, giving x = 2.' },

  // ---------------- ENGLISH · EASY ----------------
  { id: 'e-e-1', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct verb: 'The group of students ___ excited about the field trip.'",
    choices: ['is', 'are', 'were', 'be'], answer: 0,
    explanation: "'Group' is a singular collective noun, so it takes the singular verb 'is'." },
  { id: 'e-e-2', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence is punctuated correctly?',
    choices: ['I bought apples, oranges, and bananas.', 'I bought apples oranges, and bananas.', 'I bought, apples oranges and bananas.', 'I bought apples, oranges and, bananas.'], answer: 0,
    explanation: 'A comma is needed after each item in a list of three or more, including before the conjunction (the Oxford comma).' },
  { id: 'e-e-3', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'meticulous' most nearly means:",
    choices: ['careless', 'careful', 'quick', 'loud'], answer: 1,
    explanation: "'Meticulous' means showing great attention to detail; the closest synonym is 'careful'." },
  { id: 'e-e-4', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Every student must bring ___ own laptop.",
    choices: ['their', 'his or her', "they're", 'our'], answer: 1,
    explanation: "'Every student' is singular, so the traditionally correct formal pronoun is 'his or her'." },
  { id: 'e-e-5', subject: 'english', difficulty: 'easy', topic: 'Sentence Structure',
    question: 'Which is a complete sentence?',
    choices: ['Running through the park.', 'She runs through the park every morning.', 'Because she likes to run.', 'The park where she runs.'], answer: 1,
    explanation: 'Only this option has a subject and a verb forming a complete, independent thought.' },
  { id: 'e-e-6', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence uses the apostrophe correctly?',
    choices: ['The cats toy was torn.', "The cat's toy was torn.", "The cats' toy's was torn.", "The cats toys' was torn."], answer: 1,
    explanation: "A single cat possessing one toy takes an apostrophe + s: 'cat's'." },
  { id: 'e-e-7', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'reluctant' most nearly means:",
    choices: ['eager', 'unwilling', 'curious', 'angry'], answer: 1,
    explanation: "'Reluctant' means hesitant or unwilling to do something." },
  { id: 'e-e-8', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence correctly uses a comma?',
    choices: ['After the movie we went to dinner.', 'After the movie, we went to dinner.', 'After, the movie we went to dinner.', 'After the movie we, went to dinner.'], answer: 1,
    explanation: 'A comma follows an introductory phrase before the main clause begins.' },
  { id: 'e-e-9', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Choose the correct verb: \'Neither of the answers ___ correct.\'',
    choices: ['is', 'are', 'were', 'be'], answer: 0,
    explanation: "'Neither' is singular, so it takes the singular verb 'is.'" },
  { id: 'e-e-10', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Which sentence is grammatically correct?',
    choices: ['Me and him went to the store.', 'He and I went to the store.', 'Him and me went to the store.', 'I and he went to the store.'], answer: 1,
    explanation: "Subject pronouns 'he' and 'I' are correct as the subject of the sentence, in the conventional order." },
  { id: 'e-e-11', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'ancient' most nearly means:",
    choices: ['modern', 'old', 'new', 'temporary'], answer: 1,
    explanation: "'Ancient' means very old, belonging to the distant past." },
  { id: 'e-e-12', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Which sentence uses correct subject-verb agreement?',
    choices: ['The list of items are on the table.', 'The list of items is on the table.', 'The list of items were on the table.', 'The list of items be on the table.'], answer: 1,
    explanation: "The subject is 'list' (singular), not 'items,' so the singular verb 'is' is correct." },
  { id: 'e-e-13', subject: 'english', difficulty: 'easy', topic: 'Spelling',
    question: 'Choose the correctly spelled word.',
    choices: ['recieve', 'receive', 'receeve', 'receve'], answer: 1,
    explanation: "The correct spelling follows 'i before e except after c': receive." },
  { id: 'e-e-14', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence correctly punctuates a direct quotation?',
    choices: ['She said I will be there soon.', 'She said, "I will be there soon."', 'She said "I will be there soon."', 'She said, I will be there soon.'], answer: 1,
    explanation: 'A comma introduces the quotation, and quotation marks enclose the exact words spoken.' },
  { id: 'e-e-15', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'generous' most nearly means:",
    choices: ['stingy', 'giving', 'cruel', 'timid'], answer: 1,
    explanation: "'Generous' describes someone willing to give freely." },
  { id: 'e-e-16', subject: 'english', difficulty: 'easy', topic: 'Sentence Structure',
    question: 'Which sentence is a complete, correctly punctuated sentence?',
    choices: ['Although she was tired.', 'She was tired, but she kept working.', 'She was tired but kept, working.', 'Tired she kept working, although.'], answer: 1,
    explanation: 'This option joins two independent clauses correctly with a comma and coordinating conjunction.' },
  { id: 'e-e-17', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct pronoun: 'Give the book to ___.'",
    choices: ['I', 'me', 'myself', 'mine'], answer: 1,
    explanation: "'Me' is the correct object pronoun following the preposition 'to.'" },
  { id: 'e-e-18', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Which word correctly completes the sentence? 'The weather today is ___ than yesterday.'",
    choices: ['colder', 'more colder', 'most cold', 'coldest'], answer: 0,
    explanation: "'Colder' is the correct comparative form; 'more colder' is redundant." },

  // ---------------- ENGLISH · MEDIUM ----------------
  { id: 'e-m-1', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The team practiced for months; ___, they lost the championship game.',
    choices: ['therefore', 'however', 'moreover', 'for example'], answer: 1,
    explanation: "'However' signals the contrast between practicing hard and still losing." },
  { id: 'e-m-2', subject: 'english', difficulty: 'medium', topic: 'Parallelism',
    question: 'Which sentence demonstrates correct parallel structure?',
    choices: ['She likes swimming, biking, and to run.', 'She likes swimming, biking, and running.', 'She likes to swim, biking, and running.', 'She likes to swim, to bike, and running.'], answer: 1,
    explanation: 'All three items in the list should share the same grammatical form: swimming, biking, running.' },
  { id: 'e-m-3', subject: 'english', difficulty: 'medium', topic: 'Modifiers',
    question: 'Which sentence avoids a dangling modifier?',
    choices: ['Walking to school, the rain began to fall.', 'Walking to school, I got caught in the rain.', 'The rain, walking to school, began to fall.', 'Walking to school the rain fell on me.'], answer: 1,
    explanation: "The introductory phrase 'walking to school' must describe the subject that follows it — here, 'I', not the rain." },
  { id: 'e-m-4', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Although solar panels have become significantly cheaper over the past decade, many homeowners still hesitate to install them, citing the high upfront cost as a barrier despite long-term savings on energy bills." According to the passage, why do many homeowners hesitate to install solar panels?',
    choices: ["They don't believe solar panels save money.", 'The upfront cost concerns them despite long-term savings.', 'Solar panels have become more expensive.', 'They are unaware solar panels exist.'], answer: 1,
    explanation: 'The passage states the high upfront cost is the barrier, even though there are long-term savings.' },
  { id: 'e-m-5', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The bridge was closed for repairs; ___, commuters had to take a longer route to work.',
    choices: ['similarly', 'as a result', 'in contrast', 'for instance'], answer: 1,
    explanation: "'As a result' correctly shows the closure caused the longer commute." },
  { id: 'e-m-6', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which word best completes the sentence in a formal tone? 'The committee's decision was ___ by all members present.'",
    choices: ['okayed', 'approved', 'given thumbs up', 'agreed to sorta'], answer: 1,
    explanation: "'Approved' is the formal, precise word choice appropriate for the context." },
  { id: 'e-m-7', subject: 'english', difficulty: 'medium', topic: 'Verb Tense',
    question: 'Which sentence has consistent verb tense?',
    choices: ['She finished her homework and goes to bed.', 'She finishes her homework and went to bed.', 'She finished her homework and went to bed.', 'She finish her homework and went to bed.'], answer: 2,
    explanation: 'Both verbs should be in the same (past) tense: finished, went.' },
  { id: 'e-m-8', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Despite initial skepticism from critics, the museum\'s new exhibit on ancient trade routes has drawn record crowds, suggesting that public interest in history may be stronger than experts previously assumed." What can be inferred from the passage?',
    choices: ['Critics were correct that the exhibit would fail.', 'Public interest in history might be greater than experts thought.', 'The museum plans to close the exhibit early.', 'Ancient trade routes are no longer a popular topic.'], answer: 1,
    explanation: 'The record crowds despite skepticism suggest public interest exceeded expert expectations.' },
  { id: 'e-m-9', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The experiment produced unexpected results; ___, the researchers decided to repeat it under stricter conditions.',
    choices: ['consequently', 'meanwhile', 'in addition', 'on the other hand'], answer: 0,
    explanation: "'Consequently' correctly shows that the unexpected results led directly to the decision to repeat the experiment." },
  { id: 'e-m-10', subject: 'english', difficulty: 'medium', topic: 'Parallelism',
    question: 'Which sentence is parallel?',
    choices: ['The coach asked the players to run faster, jump higher, and to be more focused.', 'The coach asked the players to run faster, jump higher, and focus more.', 'The coach asked the players running faster, jumping higher, and to focus more.', 'The coach asked the players to running faster, jump higher, and focus more.'], answer: 1,
    explanation: "All three verbs following 'to' should share the same infinitive form: run, jump, focus." },
  { id: 'e-m-11', subject: 'english', difficulty: 'medium', topic: 'Modifiers',
    question: 'Which sentence correctly places the modifier to convey that she was the only person to answer correctly?',
    choices: ['Only she answered the question correctly.', 'She only answered the question correctly.', 'She answered only the question correctly.', 'She answered the question only correctly.'], answer: 0,
    explanation: "Placing 'only' directly before 'she' correctly conveys that she alone answered correctly." },
  { id: 'e-m-12', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "While many assume that a larger vocabulary is the primary driver of strong writing, experienced editors often note that clarity and sentence rhythm matter more than word choice alone." According to the passage, experienced editors believe that:',
    choices: ['vocabulary size is irrelevant to writing quality.', 'clarity and rhythm are more important than vocabulary alone.', 'larger vocabularies always produce clearer writing.', 'sentence rhythm has no effect on writing quality.'], answer: 1,
    explanation: 'The passage states editors believe clarity and rhythm "matter more than word choice alone," not that vocabulary is irrelevant.' },
  { id: 'e-m-13', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which word best fits in a formal essay? 'The results of the study were ___ significant.'",
    choices: ['kinda', 'statistically', 'super', 'sort of'], answer: 1,
    explanation: "'Statistically' is the precise, formal term used to describe significance in research contexts." },
  { id: 'e-m-14', subject: 'english', difficulty: 'medium', topic: 'Verb Tense',
    question: 'Which sentence maintains correct and consistent verb tense?',
    choices: ['By the time she arrived, the meeting had already started.', 'By the time she arrives, the meeting had already started.', 'By the time she arrived, the meeting has already started.', 'By the time she arrive, the meeting started.'], answer: 0,
    explanation: "The past perfect 'had started' correctly shows an action completed before another past action ('arrived')." },
  { id: 'e-m-15', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: "The company's profits declined sharply; ___, it announced a hiring freeze.",
    choices: ['as a result', 'similarly', 'for instance', 'nonetheless'], answer: 0,
    explanation: "'As a result' correctly shows the profit decline caused the hiring freeze." },
  { id: 'e-m-16', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Urban planners increasingly favor mixed-use developments, which combine residential, commercial, and recreational spaces within a single area, arguing that such designs reduce commute times and foster community interaction." According to the passage, urban planners favor mixed-use developments because they:',
    choices: ['increase the cost of housing.', 'reduce commute times and encourage community interaction.', 'separate residential and commercial spaces more clearly.', 'eliminate the need for public transportation.'], answer: 1,
    explanation: 'The passage directly states these designs "reduce commute times and foster community interaction."' },
  { id: 'e-m-17', subject: 'english', difficulty: 'medium', topic: 'Punctuation',
    question: 'Which sentence is correctly punctuated?',
    choices: ['My favorite subjects are, math, science, and history.', 'My favorite subjects are math, science, and history.', 'My favorite subjects, are math, science, and history.', 'My favorite subjects are math science, and history.'], answer: 1,
    explanation: 'No comma should separate a verb from its list of objects; commas are only needed between list items.' },
  { id: 'e-m-18', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which revision best improves the formality of the sentence 'The manager said the deal was a done deal'?",
    choices: ['The manager said the deal was totally finished.', 'The manager confirmed that the agreement was finalized.', 'The manager said the deal was, like, done.', 'The manager said the deal was wrapped up.'], answer: 1,
    explanation: "'Confirmed' and 'finalized' are precise, formal word choices appropriate for professional writing." },

  // ---------------- ENGLISH · HARD ----------------
  { id: 'e-h-1', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "Though the committee's report was ostensibly balanced, careful readers detected a subtle bias that rendered its conclusions ___.",
    choices: ['unimpeachable', 'tendentious', 'exhaustive', 'redundant'], answer: 1,
    explanation: "'Tendentious' means promoting a particular, biased point of view — matching the 'subtle bias' described despite the report's apparent balance." },
  { id: 'e-h-2', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: 'Which sentence correctly uses the subjunctive mood?',
    choices: ['If I was rich, I would travel the world.', 'If I were rich, I would travel the world.', 'If I am rich, I would travel the world.', 'If I will be rich, I would travel the world.'], answer: 1,
    explanation: "The subjunctive mood for hypothetical conditions uses 'were' regardless of subject: 'If I were rich...'" },
  { id: 'e-h-3', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: "A student is writing a report and wants to emphasize a contrast between two studies' findings. Which transition should be used?",
    choices: ['additionally', 'similarly', 'conversely', 'consequently'], answer: 2,
    explanation: "'Conversely' signals a direct contrast between two ideas." },
  { id: 'e-h-4', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: 'Passage: "The novelist\'s early works were dismissed by critics at the time as derivative pastiches of more established authors, their apparent debts to prior literary traditions overshadowing, in the critics\' eyes, any originality; yet a close reading — attentive to the era\'s narrow critical vocabulary for innovation — reveals subtle structural experiments that would later influence an entire generation of writers, suggesting the initial dismissal reflected the limits of contemporary criticism more than the works themselves." The passage suggests that the initial critical dismissal of the novelist\'s early works primarily reflected:',
    choices: ["a deliberate campaign to suppress the novelist's career.", "limitations in the critical standards of the time rather than the works' actual quality.", 'accurate judgments that were later reversed for sentimental reasons.', "the novelist's own dissatisfaction with the work."], answer: 1,
    explanation: 'The passage states the dismissal "reflected the limits of contemporary criticism more than the works themselves" — the critics\' narrow standards, not the writing itself, were the issue.' },
  { id: 'e-h-5', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The politician's speech was criticized as ___, full of vague promises but no concrete plans.",
    choices: ['substantive', 'platitudinous', 'meticulous', 'concise'], answer: 1,
    explanation: "'Platitudinous' means full of empty, overused statements — matching 'vague promises but no concrete plans.'" },
  { id: 'e-h-6', subject: 'english', difficulty: 'hard', topic: 'Modifiers',
    question: 'Which sentence is free of a misplaced modifier?',
    choices: ['The professor discussed the theory in the lecture that was widely debated.', 'The professor discussed, in the lecture, the theory that was widely debated.', 'In the lecture, the professor discussed the theory that was widely debated.', 'The theory, the professor discussed in the lecture widely debated.'], answer: 2,
    explanation: "Placing 'in the lecture' clearly at the start avoids ambiguity about what was 'widely debated' — the theory, not the lecture." },
  { id: 'e-h-7', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: 'A writer wants to cite a statistic to support the claim that renewable energy adoption is accelerating. Which sentence best achieves this goal?',
    choices: ['Renewable energy is good for the environment.', 'According to a 2024 report, global solar capacity increased by 35% in a single year.', 'Many people like renewable energy.', 'Renewable energy has existed for decades.'], answer: 1,
    explanation: 'Only this option provides a specific, cited statistic supporting the claim of accelerating adoption.' },
  { id: 'e-h-8', subject: 'english', difficulty: 'hard', topic: 'Parallelism',
    question: 'Which sentence correctly uses parallel structure with correlative conjunctions?',
    choices: ['She not only enjoys reading but also to write.', 'She not only enjoys reading but also enjoys writing.', 'Not only she enjoys reading but also writing.', 'She enjoys not only reading but also to writing.'], answer: 1,
    explanation: "With 'not only...but also', both halves should match grammatically: 'enjoys reading' / 'enjoys writing.'" },
  { id: 'e-h-9', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The critic's review was intentionally ___, offering praise and criticism in equal measure so as to avoid appearing biased toward either the studio or independent filmmakers.",
    choices: ['scathing', 'equivocal', 'effusive', 'derivative'], answer: 1,
    explanation: "'Equivocal' means deliberately ambiguous or noncommittal, matching the balance of praise and criticism described." },
  { id: 'e-h-10', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: "The collection of rare manuscripts, along with several first-edition novels, ___ housed in the university's special archive.",
    choices: ['are', 'is', 'were', 'have been'], answer: 1,
    explanation: "The subject is the singular 'collection'; the phrase 'along with several first-edition novels' does not change the verb's number, so 'is' is correct." },
  { id: 'e-h-11', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: 'A student wants to support the claim that urban green spaces improve mental health by citing a specific study. Which sentence best achieves this goal?',
    choices: ['Parks are nice places to relax.', 'A 2023 study found that residents living near urban parks reported 20% lower anxiety levels than those without such access.', 'Many cities are building more parks.', 'Green spaces have existed in cities for centuries.'], answer: 1,
    explanation: 'Only this option cites a specific, sourced statistic directly supporting the claim.' },
  { id: 'e-h-12', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: 'Passage: "Economists have long debated whether technological automation displaces workers permanently or merely shifts employment toward new sectors; historical precedent from the industrial revolution suggests the latter, yet critics argue that the speed and scope of contemporary automation may outpace the economy\'s historical capacity to generate replacement jobs." The passage suggests that critics of the historical-precedent argument believe:',
    choices: ['automation has never displaced workers in the past.', "the current pace of automation may exceed the economy's ability to adapt as it did historically.", 'new sectors will definitely absorb all displaced workers.', 'the industrial revolution created no new jobs.'], answer: 1,
    explanation: 'The passage states critics worry contemporary automation\'s "speed and scope" may "outpace the economy\'s historical capacity to generate replacement jobs."' },
  { id: 'e-h-13', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: 'Despite the mounting evidence against his theory, the researcher remained ___, refusing to consider any alternative explanation.',
    choices: ['ambivalent', 'intransigent', 'indifferent', 'receptive'], answer: 1,
    explanation: "'Intransigent' means stubbornly unwilling to change one's views, matching the refusal to consider alternatives." },
  { id: 'e-h-14', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: 'Which sentence corrects the comma splice?',
    choices: ['The experiment failed, the hypothesis was clearly flawed.', 'The experiment failed; the hypothesis was clearly flawed.', 'The experiment failed the hypothesis was clearly flawed.', 'The experiment, failed, the hypothesis was clearly flawed.'], answer: 1,
    explanation: 'A semicolon correctly joins two independent clauses without a coordinating conjunction.' },
  { id: 'e-h-15', subject: 'english', difficulty: 'hard', topic: 'Transitions',
    question: 'The new policy reduced emissions significantly; ___, it raised production costs for smaller manufacturers.',
    choices: ['consequently', 'nevertheless', 'for example', 'similarly'], answer: 1,
    explanation: "'Nevertheless' signals the concession between a positive effect (reduced emissions) and a negative one (higher costs)." },
  { id: 'e-h-16', subject: 'english', difficulty: 'hard', topic: 'Punctuation',
    question: 'Which sentence uses punctuation correctly?',
    choices: ['The committee reached a decision; approve the new budget.', 'The committee reached a decision: approve the new budget.', 'The committee reached a decision, approve the new budget.', 'The committee reached a decision - : approve the new budget.'], answer: 1,
    explanation: 'A colon correctly introduces an explanation or elaboration of the preceding independent clause.' },
  { id: 'e-h-17', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: 'Passage: "While proponents of standardized testing argue that it provides an objective, comparable measure of student achievement across diverse school systems, opponents contend that such tests often reflect socioeconomic advantages more than actual learning, since students from wealthier backgrounds typically have greater access to test preparation resources." According to the passage, opponents of standardized testing argue that test scores may primarily reflect:',
    choices: ["a student's natural intelligence.", 'the quality of a school\'s teaching alone.', 'socioeconomic advantages such as access to test preparation.', 'the difficulty of the test itself.'], answer: 2,
    explanation: 'The passage states opponents believe scores reflect "socioeconomic advantages more than actual learning," citing test-prep access specifically.' },
  { id: 'e-h-18', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The ambassador's remarks were carefully ___, conveying disapproval without ever using an accusatory tone.",
    choices: ['vitriolic', 'measured', 'incendiary', 'apathetic'], answer: 1,
    explanation: "'Measured' means carefully controlled and restrained, matching the deliberate, non-accusatory tone described." },
];
