// SAT Prep — starter question bank
// Each question: { id, subject: 'math'|'english', difficulty: 'easy'|'medium'|'hard',
//                   topic, question, choices: [4], answer: index, explanation }

const QUESTIONS = [
  // ---------------- MATH · EASY ----------------
  { id: 'm-e-1', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'If x + 8 = 20, what is the value of x?',
    choices: ['10', '12', '14', '28'], answer: 1,
    explanation: 'Subtract 8 from both sides: x = 20 - 8 = 12.' },
  { id: 'm-e-2', subject: 'math', difficulty: 'easy', topic: 'Percentages', noCalcEligible: true,
    question: 'What is 15% of 200?',
    choices: ['20', '25', '30', '35'], answer: 2,
    explanation: '15% of 200 = 0.15 × 200 = 30.' },
  { id: 'm-e-3', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'Solve for x: 3x - 5 = 16',
    choices: ['5', '6', '7', '8'], answer: 2,
    explanation: 'Add 5 to both sides: 3x = 21. Divide by 3: x = 7.' },
  { id: 'm-e-4', subject: 'math', difficulty: 'easy', topic: 'Ratios', noCalcEligible: true,
    question: 'A recipe calls for 2 cups of flour for every 3 cups of sugar. If you use 6 cups of sugar, how many cups of flour do you need?',
    choices: ['3', '4', '5', '6'], answer: 1,
    explanation: 'The ratio 2:3 scales to 4:6, so 4 cups of flour are needed.' },
  { id: 'm-e-5', subject: 'math', difficulty: 'easy', topic: 'Arithmetic', noCalcEligible: true,
    question: 'What is the average (arithmetic mean) of 4, 8, and 12?',
    choices: ['6', '7', '8', '9'], answer: 2,
    explanation: 'Sum = 24, divided by 3 values = 8.' },
  { id: 'm-e-6', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'If 5y = 45, what is the value of y?',
    choices: ['7', '8', '9', '10'], answer: 2,
    explanation: 'Divide both sides by 5: y = 45 / 5 = 9.' },
  { id: 'm-e-7', subject: 'math', difficulty: 'easy', topic: 'Percentages', noCalcEligible: true,
    question: 'A shirt originally costs $40. After a 25% discount, what is the sale price?',
    choices: ['$25', '$28', '$30', '$32'], answer: 2,
    explanation: '25% of $40 is $10. $40 - $10 = $30.' },
  { id: 'm-e-8', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'Solve for x: x / 4 = 9',
    choices: ['13', '24', '36', '40'], answer: 2,
    explanation: 'Multiply both sides by 4: x = 9 × 4 = 36.' },
  { id: 'm-e-9', subject: 'math', difficulty: 'easy', topic: 'Fractions and Decimals', noCalcEligible: true,
    question: 'What is 3/4 expressed as a decimal?',
    choices: ['0.34', '0.75', '1.34', '0.43'], answer: 1,
    explanation: '3 divided by 4 equals 0.75.' },
  { id: 'm-e-10', subject: 'math', difficulty: 'easy', topic: 'Geometry', noCalcEligible: true,
    question: 'If a triangle has sides of length 5, 12, and 13, what is its perimeter?',
    choices: ['25', '28', '30', '32'], answer: 2,
    explanation: 'Perimeter = 5 + 12 + 13 = 30.' },
  { id: 'm-e-11', subject: 'math', difficulty: 'easy', topic: 'Inequalities', noCalcEligible: true,
    question: 'Which value of x satisfies 2x + 3 < 11?',
    choices: ['3', '4', '5', '6'], answer: 0,
    explanation: '2x + 3 < 11 → 2x < 8 → x < 4. Only 3 is less than 4.' },
  { id: 'm-e-12', subject: 'math', difficulty: 'easy', topic: 'Arithmetic',
    question: 'A store sells notebooks for $2.50 each. How much do 6 notebooks cost?',
    choices: ['$12', '$13.50', '$15', '$17.50'], answer: 2,
    explanation: '6 × $2.50 = $15.' },
  { id: 'm-e-13', subject: 'math', difficulty: 'easy', topic: 'Exponents', noCalcEligible: true,
    question: 'What is the value of 4² - 3²?',
    choices: ['1', '5', '7', '9'], answer: 2,
    explanation: '16 - 9 = 7.' },
  { id: 'm-e-14', subject: 'math', difficulty: 'easy', topic: 'Rates',
    question: 'If a car travels at a constant speed of 50 miles per hour, how far does it travel in 2.5 hours?',
    choices: ['100', '110', '125', '150'], answer: 2,
    explanation: '50 × 2.5 = 125 miles.' },
  { id: 'm-e-15', subject: 'math', difficulty: 'easy', topic: 'Unit Conversion', noCalcEligible: true,
    question: 'Convert 3 feet 6 inches to inches.',
    choices: ['36', '40', '42', '48'], answer: 2,
    explanation: '3 feet = 36 inches. 36 + 6 = 42 inches.' },
  { id: 'm-e-16', subject: 'math', difficulty: 'easy', topic: 'Number Theory', noCalcEligible: true,
    question: 'What is the least common multiple of 4 and 6?',
    choices: ['8', '10', '12', '24'], answer: 2,
    explanation: 'Multiples of 4: 4, 8, 12... Multiples of 6: 6, 12... The smallest shared multiple is 12.' },
  { id: 'm-e-17', subject: 'math', difficulty: 'easy', topic: 'Probability', noCalcEligible: true,
    question: 'A jar contains 5 green and 5 yellow candies. What is the probability of picking a yellow candy at random?',
    choices: ['1/4', '1/3', '1/2', '2/3'], answer: 2,
    explanation: 'There are 5 yellow candies out of 10 total, so the probability is 5/10 = 1/2.' },
  { id: 'm-e-18', subject: 'math', difficulty: 'easy', topic: 'Order of Operations', noCalcEligible: true,
    question: 'Simplify: 6 + 2 × 3',
    choices: ['12', '18', '24', '8'], answer: 0,
    explanation: 'Multiplication before addition: 2 × 3 = 6, then 6 + 6 = 12.' },
  { id: 'm-e-19', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'If 7x = 63, what is the value of x?',
    choices: ['7', '8', '9', '10'], answer: 2,
    explanation: 'Divide both sides by 7: x = 63 / 7 = 9.' },
  { id: 'm-e-20', subject: 'math', difficulty: 'easy', topic: 'Percentages', noCalcEligible: true,
    question: 'What is 40% of 150?',
    choices: ['50', '55', '60', '65'], answer: 2,
    explanation: '40% of 150 = 0.4 × 150 = 60.' },
  { id: 'm-e-21', subject: 'math', difficulty: 'easy', topic: 'Fractions', noCalcEligible: true,
    question: 'A pizza is cut into 8 equal slices. If 3 slices are eaten, what fraction of the pizza remains?',
    choices: ['3/8', '4/8', '5/8', '6/8'], answer: 2,
    explanation: '8 - 3 = 5 slices remain, so 5/8 of the pizza is left.' },
  { id: 'm-e-22', subject: 'math', difficulty: 'easy', topic: 'Linear Equations', noCalcEligible: true,
    question: 'Solve for x: x - 15 = 22',
    choices: ['27', '32', '37', '42'], answer: 2,
    explanation: 'Add 15 to both sides: x = 22 + 15 = 37.' },
  { id: 'm-e-23', subject: 'math', difficulty: 'easy', topic: 'Rates',
    question: 'A car gets 30 miles per gallon. How many miles can it travel on 8 gallons?',
    choices: ['200', '220', '240', '260'], answer: 2,
    explanation: '30 × 8 = 240 miles.' },
  { id: 'm-e-24', subject: 'math', difficulty: 'easy', topic: 'Geometry', noCalcEligible: true,
    question: 'What is the perimeter of a square with side length 9?',
    choices: ['18', '27', '36', '45'], answer: 2,
    explanation: 'Perimeter of a square = 4 × side = 4 × 9 = 36.' },
  { id: 'm-e-25', subject: 'math', difficulty: 'easy', topic: 'Percentages',
    question: 'If a shirt costs $25 and sales tax is 8%, what is the total cost?',
    choices: ['$26.00', '$26.50', '$27.00', '$27.50'], answer: 2,
    explanation: '$25 × 1.08 = $27.00.' },
  { id: 'm-e-26', subject: 'math', difficulty: 'easy', topic: 'Statistics', noCalcEligible: true,
    question: 'What is the median of the numbers 3, 7, 9, 12, 15?',
    choices: ['7', '9', '12', '15'], answer: 1,
    explanation: 'With the numbers already in order, the middle value is 9.' },
  { id: 'm-e-27', subject: 'math', difficulty: 'easy', topic: 'Exponents', noCalcEligible: true,
    question: 'Simplify: 5²',
    choices: ['10', '15', '20', '25'], answer: 3,
    explanation: '5² = 5 × 5 = 25.' },
  { id: 'm-e-28', subject: 'math', difficulty: 'easy', topic: 'Probability', noCalcEligible: true,
    question: 'A bag has 3 red, 4 blue, and 3 green marbles. What is the probability of picking a blue marble at random?',
    choices: ['1/5', '3/10', '2/5', '1/2'], answer: 2,
    explanation: 'There are 4 blue marbles out of 10 total, so the probability is 4/10 = 2/5.' },

  // ---------------- MATH · MEDIUM ----------------
  { id: 'm-m-1', subject: 'math', difficulty: 'medium', topic: 'Systems of Equations', noCalcEligible: true,
    question: 'If 2x + y = 11 and x - y = 1, what is the value of x?',
    choices: ['3', '4', '5', '6'], answer: 1,
    explanation: 'From x - y = 1, y = x - 1. Substituting: 2x + (x - 1) = 11 → 3x = 12 → x = 4.' },
  { id: 'm-m-2', subject: 'math', difficulty: 'medium', topic: 'Quadratics', noCalcEligible: true,
    question: 'Which of the following is a solution to x² - 5x + 6 = 0?',
    choices: ['1', '2', '4', '6'], answer: 1,
    explanation: 'Factoring gives (x - 2)(x - 3) = 0, so x = 2 or x = 3. Only 2 appears among the choices.' },
  { id: 'm-m-3', subject: 'math', difficulty: 'medium', topic: 'Geometry', noCalcEligible: true,
    question: 'A rectangle has a length of 12 and a width of 7. What is its area?',
    choices: ['70', '77', '84', '91'], answer: 2,
    explanation: 'Area = length × width = 12 × 7 = 84.' },
  { id: 'm-m-4', subject: 'math', difficulty: 'medium', topic: 'Geometry', noCalcEligible: true,
    question: 'A circle has a radius of 5. What is its circumference in terms of π?',
    choices: ['5π', '10π', '15π', '25π'], answer: 1,
    explanation: 'Circumference = 2πr = 2π(5) = 10π.' },
  { id: 'm-m-5', subject: 'math', difficulty: 'medium', topic: 'Exponents', noCalcEligible: true,
    question: 'Simplify: (2³)(2⁴)',
    choices: ['64', '128', '256', '512'], answer: 1,
    explanation: 'Add exponents when multiplying same base: 2³⁺⁴ = 2⁷ = 128.' },
  { id: 'm-m-6', subject: 'math', difficulty: 'medium', topic: 'Rates',
    question: 'A car travels 180 miles in 3 hours. At this rate, how many miles will it travel in 5 hours?',
    choices: ['270', '290', '300', '320'], answer: 2,
    explanation: 'Rate = 180 / 3 = 60 mph. In 5 hours: 60 × 5 = 300 miles.' },
  { id: 'm-m-7', subject: 'math', difficulty: 'medium', topic: 'Geometry',
    question: 'A rectangular box has dimensions 4 by 5 by 6. What is its volume?',
    choices: ['100', '110', '120', '130'], answer: 2,
    explanation: 'Volume = 4 × 5 × 6 = 120.' },
  { id: 'm-m-8', subject: 'math', difficulty: 'medium', topic: 'Systems of Equations',
    question: 'Tickets to a show cost $8 for adults and $5 for children. If 10 tickets were sold for a total of $65, how many child tickets were sold?',
    choices: ['3', '4', '5', '6'], answer: 2,
    explanation: 'Let a + c = 10 and 8a + 5c = 65. Substituting a = 10 - c gives 80 - 8c + 5c = 65 → -3c = -15 → c = 5.' },
  { id: 'm-m-9', subject: 'math', difficulty: 'medium', topic: 'Direct Variation', noCalcEligible: true,
    question: 'If y varies directly with x, and y = 20 when x = 4, what is y when x = 9?',
    choices: ['36', '40', '45', '49'], answer: 2,
    explanation: 'y = kx, so 20 = k(4) → k = 5. When x = 9, y = 5 × 9 = 45.' },
  { id: 'm-m-10', subject: 'math', difficulty: 'medium', topic: 'Similar Triangles', noCalcEligible: true,
    question: 'Two triangles are similar with a scale factor of 3. If the smaller triangle has a side length of 4, what is the corresponding side length in the larger triangle?',
    choices: ['7', '9', '12', '15'], answer: 2,
    explanation: 'Similar triangles scale proportionally: 4 × 3 = 12.' },
  { id: 'm-m-11', subject: 'math', difficulty: 'medium', topic: 'Simple Interest',
    question: 'A bank account earns 5% simple interest per year. If $2000 is deposited, how much interest is earned after 3 years?',
    choices: ['$100', '$200', '$300', '$400'], answer: 2,
    explanation: 'Simple interest = principal × rate × time = 2000 × 0.05 × 3 = $300.' },
  { id: 'm-m-12', subject: 'math', difficulty: 'medium', topic: 'Statistics', noCalcEligible: true,
    question: 'The mean of five numbers is 20. If four of the numbers are 15, 18, 22, and 25, what is the fifth number?',
    choices: ['15', '18', '20', '22'], answer: 2,
    explanation: 'The five numbers must sum to 100. 15 + 18 + 22 + 25 = 80, so the fifth number is 100 - 80 = 20.' },
  { id: 'm-m-13', subject: 'math', difficulty: 'medium', topic: 'Absolute Value', noCalcEligible: true,
    question: 'Which value of x satisfies |x - 4| = 10?',
    choices: ['-6', '-4', '4', '6'], answer: 0,
    explanation: 'x - 4 = -10 → x = -6 (or x - 4 = 10 → x = 14, not listed). Checking: |-6 - 4| = |-10| = 10. ✓' },
  { id: 'm-m-14', subject: 'math', difficulty: 'medium', topic: 'Polynomial Expansion', noCalcEligible: true,
    question: 'Which expression is equivalent to (x + 4)(x - 2)?',
    choices: ['x² + 2x - 8', 'x² - 2x + 8', 'x² + 6x - 8', 'x² - 6x - 8'], answer: 0,
    explanation: 'Using FOIL: x² - 2x + 4x - 8 = x² + 2x - 8.' },
  { id: 'm-m-15', subject: 'math', difficulty: 'medium', topic: 'Scale and Ratios',
    question: 'A map has a scale of 1 inch = 25 miles. If two cities are 4.5 inches apart on the map, what is the actual distance between them?',
    choices: ['100', '110', '112.5', '125'], answer: 2,
    explanation: '4.5 × 25 = 112.5 miles.' },
  { id: 'm-m-16', subject: 'math', difficulty: 'medium', topic: 'Angle Relationships', noCalcEligible: true,
    question: 'Two angles are supplementary. If one angle measures 65°, what is the measure of the other angle?',
    choices: ['105°', '115°', '125°', '135°'], answer: 1,
    explanation: 'Supplementary angles sum to 180°. 180 - 65 = 115.' },
  { id: 'm-m-17', subject: 'math', difficulty: 'medium', topic: 'Ratios',
    question: 'A recipe requires 3/4 cup of sugar for 12 cookies. How much sugar is needed for 20 cookies, assuming a constant ratio?',
    choices: ['1', '1.1', '1.25', '1.5'], answer: 2,
    explanation: 'Sugar per cookie = (3/4) / 12. For 20 cookies: (3/4) × (20/12) = (3/4) × (5/3) = 15/12 = 1.25 cups.' },
  { id: 'm-m-18', subject: 'math', difficulty: 'medium', topic: 'Inverse Variation', noCalcEligible: true,
    question: 'If x varies inversely with y, and x = 8 when y = 3, what is x when y = 6?',
    choices: ['2', '4', '6', '8'], answer: 1,
    explanation: 'xy = k = 8 × 3 = 24. When y = 6, x = 24 / 6 = 4.' },
  { id: 'm-m-19', subject: 'math', difficulty: 'medium', topic: 'Systems of Equations', noCalcEligible: true,
    question: 'If 3x - 2y = 12 and x = 4, what is the value of y?',
    choices: ['-2', '0', '2', '4'], answer: 1,
    explanation: 'Substitute x = 4: 3(4) - 2y = 12 → 12 - 2y = 12 → y = 0.' },
  { id: 'm-m-20', subject: 'math', difficulty: 'medium', topic: 'Percent Change',
    question: 'A population increased from 200 to 250. What is the percent increase?',
    choices: ['20%', '25%', '30%', '50%'], answer: 1,
    explanation: 'The increase is 50. Percent increase = 50/200 × 100 = 25%.' },
  { id: 'm-m-21', subject: 'math', difficulty: 'medium', topic: 'Geometry', noCalcEligible: true,
    question: 'A triangle has a base of 10 and a height of 6. What is its area?',
    choices: ['16', '30', '40', '60'], answer: 1,
    explanation: 'Area = (1/2) × base × height = (1/2) × 10 × 6 = 30.' },
  { id: 'm-m-22', subject: 'math', difficulty: 'medium', topic: 'Rates',
    question: 'Two trains leave the same station traveling in opposite directions, one at 60 mph and the other at 40 mph. After how many hours will they be 300 miles apart?',
    choices: ['2', '2.5', '3', '3.5'], answer: 2,
    explanation: 'Combined speed = 100 mph. Time = 300 / 100 = 3 hours.' },
  { id: 'm-m-23', subject: 'math', difficulty: 'medium', topic: 'Exponents', noCalcEligible: true,
    question: 'Simplify: (3²)(3⁻¹)',
    choices: ['1', '3', '9', '27'], answer: 1,
    explanation: 'Add exponents: 3^(2-1) = 3¹ = 3.' },
  { id: 'm-m-24', subject: 'math', difficulty: 'medium', topic: 'Quadratics', noCalcEligible: true,
    question: 'Which value of x satisfies x² - 7x + 12 = 0 and is greater than 3?',
    choices: ['2', '3', '4', '5'], answer: 2,
    explanation: 'Factoring gives (x - 3)(x - 4) = 0, so x = 3 or x = 4. Only 4 is greater than 3.' },
  { id: 'm-m-25', subject: 'math', difficulty: 'medium', topic: 'Unit Conversion', noCalcEligible: true,
    question: 'Convert 2.5 hours into minutes.',
    choices: ['120', '130', '150', '160'], answer: 2,
    explanation: '2.5 × 60 = 150 minutes.' },
  { id: 'm-m-26', subject: 'math', difficulty: 'medium', topic: 'Weighted Average',
    question: "A student scored 80 on a test worth 30% of the grade and 90 on a test worth 70% of the grade. What is the student's weighted average?",
    choices: ['83', '85', '87', '89'], answer: 2,
    explanation: '0.3 × 80 + 0.7 × 90 = 24 + 63 = 87.' },
  { id: 'm-m-27', subject: 'math', difficulty: 'medium', topic: 'Scale and Ratios',
    question: 'A map shows a scale of 1 cm = 15 km. Two towns are 3.2 cm apart on the map. What is the actual distance between them?',
    choices: ['42', '45', '48', '51'], answer: 2,
    explanation: '3.2 × 15 = 48 km.' },
  { id: 'm-m-28', subject: 'math', difficulty: 'medium', topic: 'Coordinate Geometry', noCalcEligible: true,
    question: 'What is the midpoint of the segment connecting (2, -4) and (8, 6)?',
    choices: ['(4, 1)', '(5, 1)', '(5, 2)', '(6, 1)'], answer: 1,
    explanation: 'Midpoint = ((2+8)/2, (-4+6)/2) = (5, 1).' },

  // ---------------- MATH · HARD ----------------
  { id: 'm-h-1', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'Which value of x satisfies 2x² + 3x - 2 = 0?',
    choices: ['-2', '-1', '1', '2'], answer: 0,
    explanation: 'Using the quadratic formula: x = (-3 ± √(9+16))/4 = (-3 ± 5)/4, giving x = 0.5 or x = -2. Only -2 appears among the choices.' },
  { id: 'm-h-2', subject: 'math', difficulty: 'hard', topic: 'Functions', noCalcEligible: true,
    question: 'If f(x) = 2x² - 3x + 1 and g(x) = f(x) + 4x, what is g(-1)?',
    choices: ['-2', '0', '2', '4'], answer: 2,
    explanation: 'f(-1) = 2(1) - 3(-1) + 1 = 6. Then g(-1) = f(-1) + 4(-1) = 6 - 4 = 2.' },
  { id: 'm-h-3', subject: 'math', difficulty: 'hard', topic: 'Exponential Growth',
    question: 'A population of bacteria doubles every 3 hours. If the initial population is 100, what is the population after 9 hours?',
    choices: ['300', '400', '800', '1600'], answer: 2,
    explanation: '9 hours = 3 doubling periods. 100 × 2³ = 800.' },
  { id: 'm-h-4', subject: 'math', difficulty: 'hard', topic: 'Trigonometry', noCalcEligible: true,
    question: 'In a right triangle, one angle measures 30°, and the hypotenuse is 10. What is the length of the side opposite the 30° angle?',
    choices: ['3', '5', '5√3', '10'], answer: 1,
    explanation: 'Opposite = hypotenuse × sin(30°) = 10 × 0.5 = 5.' },
  { id: 'm-h-5', subject: 'math', difficulty: 'hard', topic: 'Rational Expressions', noCalcEligible: true,
    question: 'Simplify: (x² - 9) / (x - 3), for x ≠ 3',
    choices: ['x - 3', 'x + 3', 'x² - 3', 'x + 9'], answer: 1,
    explanation: 'x² - 9 factors as (x - 3)(x + 3). Dividing by (x - 3) leaves x + 3.' },
  { id: 'm-h-6', subject: 'math', difficulty: 'hard', topic: 'Work Rate',
    question: 'Pipe A can fill a tank in 4 hours, and pipe B can fill the same tank in 6 hours. Working together, how many hours will it take to fill the tank?',
    choices: ['2', '2.4', '3', '5'], answer: 1,
    explanation: 'Combined rate = 1/4 + 1/6 = 5/12 tank per hour. Time = 12/5 = 2.4 hours.' },
  { id: 'm-h-7', subject: 'math', difficulty: 'hard', topic: 'Absolute Value Inequalities', noCalcEligible: true,
    question: 'For how many integer values of x is |3x - 4| < 11 true?',
    choices: ['5', '6', '7', '8'], answer: 2,
    explanation: 'Rewrite as -11 < 3x - 4 < 11, so -7 < 3x < 15, giving -7/3 < x < 5. The integers in that range are -2, -1, 0, 1, 2, 3, 4 — 7 values.' },
  { id: 'm-h-8', subject: 'math', difficulty: 'hard', topic: 'Coordinate Geometry',
    question: 'What is the slope of the line passing through points (2, 3) and (6, 11)?',
    choices: ['1', '2', '3', '4'], answer: 1,
    explanation: 'Slope = (11 - 3) / (6 - 2) = 8 / 4 = 2.' },
  { id: 'm-h-9', subject: 'math', difficulty: 'hard', topic: 'Quadratic-Linear Systems', noCalcEligible: true,
    question: 'If y = 2x - 3 and y = x² - 4x + 5, what is one possible value of x?',
    choices: ['1', '2', '3', '5'], answer: 1,
    explanation: 'Setting the equations equal: 2x - 3 = x² - 4x + 5 → x² - 6x + 8 = 0 → (x - 2)(x - 4) = 0, so x = 2 or x = 4. Only 2 appears among the choices.' },
  { id: 'm-h-10', subject: 'math', difficulty: 'hard', topic: 'Circle Equations', noCalcEligible: true,
    question: 'A circle is defined by the equation (x - 3)² + (y + 2)² = 25. What is the radius of the circle?',
    choices: ['4', '5', '6', '25'], answer: 1,
    explanation: 'In the standard form (x - h)² + (y - k)² = r², r² = 25, so r = 5.' },
  { id: 'm-h-11', subject: 'math', difficulty: 'hard', topic: 'Remainder Theorem', noCalcEligible: true,
    question: 'When the polynomial x³ - 2x² + kx - 6 is divided by (x - 3), the remainder is 0. What is the value of k?',
    choices: ['-3', '-1', '1', '3'], answer: 1,
    explanation: 'By the remainder theorem, substituting x = 3 must give 0: 27 - 18 + 3k - 6 = 0 → 3 + 3k = 0 → k = -1.' },
  { id: 'm-h-12', subject: 'math', difficulty: 'hard', topic: 'Exponential Decay', noCalcEligible: true,
    question: 'A car depreciates in value by 12% each year. If it is initially worth $25,000, which expression represents its value after t years?',
    choices: ['25000(0.12)^t', '25000(0.88)^t', '25000(1.12)^t', '25000 - 0.12t'], answer: 1,
    explanation: 'Losing 12% each year means 88% of the value remains, so the value after t years is 25000 multiplied by 0.88 raised to the t.' },
  { id: 'm-h-13', subject: 'math', difficulty: 'hard', topic: 'Statistics', noCalcEligible: true,
    question: 'Data set A has a mean of 50 and a standard deviation of 5. Data set B has the same mean but a standard deviation of 10. Which statement must be true?',
    choices: ['Data set A has a wider range of values than data set B.', "Data set B's values are more spread out from the mean than data set A's.", 'Data sets A and B have identical distributions.', 'Data set B has a higher mean than data set A.'], answer: 1,
    explanation: 'A larger standard deviation means the values are, on average, farther from the mean — indicating greater spread, not a different mean or a guaranteed wider range.' },
  { id: 'm-h-14', subject: 'math', difficulty: 'hard', topic: 'Sequences', noCalcEligible: true,
    question: 'In a geometric sequence, the first term is 3 and the common ratio is 2. What is the 6th term?',
    choices: ['48', '64', '96', '192'], answer: 2,
    explanation: 'The nth term is 3 × 2^(n-1). The 6th term is 3 × 2⁵ = 3 × 32 = 96.' },
  { id: 'm-h-15', subject: 'math', difficulty: 'hard', topic: 'Rational Equations', noCalcEligible: true,
    question: 'What is the solution to the equation 3/(x - 2) = 6/(x + 1), given x ≠ 2 and x ≠ -1?',
    choices: ['3', '4', '5', '6'], answer: 2,
    explanation: 'Cross-multiplying: 3(x + 1) = 6(x - 2) → 3x + 3 = 6x - 12 → -3x = -15 → x = 5.' },
  { id: 'm-h-16', subject: 'math', difficulty: 'hard', topic: 'Probability',
    question: 'A bag contains 4 red marbles and 6 blue marbles. If two marbles are drawn without replacement, what is the probability that both are red?',
    choices: ['1/15', '2/15', '3/15', '4/15'], answer: 1,
    explanation: 'P(both red) = (4/10) × (3/9) = 12/90 = 2/15.' },
  { id: 'm-h-17', subject: 'math', difficulty: 'hard', topic: 'Function Transformations', noCalcEligible: true,
    question: 'The graph of f(x) = x² is shifted 3 units right and 2 units up to create g(x). Which equation represents g(x)?',
    choices: ['(x - 3)² + 2', '(x + 3)² + 2', '(x - 3)² - 2', '(x + 3)² - 2'], answer: 0,
    explanation: 'A shift right by 3 replaces x with (x - 3); a shift up by 2 adds 2 to the result: g(x) = (x - 3)² + 2.' },
  { id: 'm-h-18', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'If 4^(x+1) = 64, what is the value of x?',
    choices: ['1', '2', '3', '4'], answer: 1,
    explanation: '64 = 4³, so x + 1 = 3, giving x = 2.' },
  { id: 'm-h-19', subject: 'math', difficulty: 'hard', topic: 'Composite Functions', noCalcEligible: true,
    question: 'If f(x) = x² - 4 and g(x) = 2x + 1, what is f(g(1))?',
    choices: ['3', '5', '7', '9'], answer: 1,
    explanation: 'g(1) = 2(1) + 1 = 3. Then f(3) = 3² - 4 = 5.' },
  { id: 'm-h-20', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'What is the vertex of the parabola y = (x - 2)² + 5?',
    choices: ['(2, 5)', '(-2, 5)', '(2, -5)', '(-2, -5)'], answer: 0,
    explanation: 'In vertex form y = (x - h)² + k, the vertex is (h, k) = (2, 5).' },
  { id: 'm-h-21', subject: 'math', difficulty: 'hard', topic: 'Coordinate Geometry', noCalcEligible: true,
    question: 'What is the distance between the points (1, 2) and (4, 6)?',
    choices: ['4', '5', '6', '7'], answer: 1,
    explanation: 'Distance = √((4-1)² + (6-2)²) = √(9 + 16) = √25 = 5.' },
  { id: 'm-h-22', subject: 'math', difficulty: 'hard', topic: 'Geometry',
    question: 'A cylindrical tank has a radius of 3 and a height of 10. What is its volume in terms of π?',
    choices: ['30π', '60π', '90π', '120π'], answer: 2,
    explanation: 'Volume = πr²h = π(3²)(10) = 90π.' },
  { id: 'm-h-23', subject: 'math', difficulty: 'hard', topic: 'Sequences', noCalcEligible: true,
    question: 'In an arithmetic sequence, the 3rd term is 11 and the 7th term is 27. What is the common difference?',
    choices: ['3', '4', '5', '6'], answer: 1,
    explanation: 'From the 3rd to the 7th term is 4 steps, covering a change of 27 - 11 = 16, so the common difference is 16/4 = 4.' },
  { id: 'm-h-24', subject: 'math', difficulty: 'hard', topic: 'Geometry', noCalcEligible: true,
    question: 'If two similar rectangular prisms have a linear scale factor of 2, what is the ratio of their volumes?',
    choices: ['2:1', '4:1', '6:1', '8:1'], answer: 3,
    explanation: 'Volume scales with the cube of the linear factor: 2³ = 8, so the ratio is 8:1.' },
  { id: 'm-h-25', subject: 'math', difficulty: 'hard', topic: 'Rational Equations', noCalcEligible: true,
    question: 'Solve for x: (x - 1)/(x + 2) = 3, given x ≠ -2',
    choices: ['-3.5', '-2.5', '2.5', '3.5'], answer: 0,
    explanation: 'Cross-multiplying: x - 1 = 3(x + 2) → x - 1 = 3x + 6 → -2x = 7 → x = -3.5.' },
  { id: 'm-h-26', subject: 'math', difficulty: 'hard', topic: 'Quadratics',
    question: "A rectangle's length is 3 more than twice its width. If the area is 65, what is the width?",
    choices: ['4', '5', '6', '7'], answer: 1,
    explanation: 'Let w be the width: w(2w + 3) = 65 → 2w² + 3w - 65 = 0. The positive solution is w = 5 (since 5 × 13 = 65).' },
  { id: 'm-h-27', subject: 'math', difficulty: 'hard', topic: 'Sequences', noCalcEligible: true,
    question: 'What is the sum of the first 10 positive even integers?',
    choices: ['100', '105', '110', '115'], answer: 2,
    explanation: '2 + 4 + ... + 20 = 2(1 + 2 + ... + 10) = 2 × 55 = 110.' },
  { id: 'm-h-28', subject: 'math', difficulty: 'hard', topic: 'Logarithms', noCalcEligible: true,
    question: 'If log₂(x) = 5, what is the value of x?',
    choices: ['10', '16', '25', '32'], answer: 3,
    explanation: 'log₂(x) = 5 means x = 2⁵ = 32.' },
  { id: 'm-h-29', subject: 'math', difficulty: 'hard', topic: 'Function Evaluation', noCalcEligible: true,
    question: 'If f(x) = 3x² - 5x + 2, what is f(-2)?',
    choices: ['14', '18', '24', '28'], answer: 2,
    explanation: 'f(-2) = 3(4) - 5(-2) + 2 = 12 + 10 + 2 = 24.' },
  { id: 'm-h-30', subject: 'math', difficulty: 'hard', topic: 'Radical Equations', noCalcEligible: true,
    question: 'Solve for x: √(2x + 7) = 5',
    choices: ['7', '8', '9', '10'], answer: 2,
    explanation: 'Squaring both sides: 2x + 7 = 25 → 2x = 18 → x = 9. Check: √(2(9)+7) = √25 = 5. ✓' },
  { id: 'm-h-31', subject: 'math', difficulty: 'hard', topic: 'Radicals', noCalcEligible: true,
    question: 'If x² = 49 and x < 0, what is the value of x?',
    choices: ['-9', '-8', '-7', '-6'], answer: 2,
    explanation: 'x = ±7, and since x < 0, x = -7.' },
  { id: 'm-h-32', subject: 'math', difficulty: 'hard', topic: 'Absolute Value', noCalcEligible: true,
    question: 'Which value of x satisfies |3x - 6| = 15?',
    choices: ['-3', '-1', '1', '3'], answer: 0,
    explanation: '3x - 6 = -15 → x = -3 (or 3x - 6 = 15 → x = 7, not listed). Check: |3(-3)-6| = |-15| = 15. ✓' },
  { id: 'm-h-33', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'If 2^(3x) = 32, what is the value of x?',
    choices: ['1', '5/3', '2', '5'], answer: 1,
    explanation: '32 = 2⁵, so 3x = 5, giving x = 5/3.' },
  { id: 'm-h-34', subject: 'math', difficulty: 'hard', topic: 'Rational Expressions', noCalcEligible: true,
    question: 'Simplify: (x² - 16)/(x - 4), for x ≠ 4',
    choices: ['x - 4', 'x + 4', 'x² - 4', 'x + 16'], answer: 1,
    explanation: 'x² - 16 factors as (x-4)(x+4). Dividing by (x-4) leaves x + 4.' },
  { id: 'm-h-35', subject: 'math', difficulty: 'hard', topic: 'Composite Functions', noCalcEligible: true,
    question: 'If f(x) = x + 3 and g(x) = x², what is g(f(2))?',
    choices: ['11', '16', '25', '36'], answer: 2,
    explanation: 'f(2) = 2 + 3 = 5. Then g(5) = 5² = 25.' },
  { id: 'm-h-36', subject: 'math', difficulty: 'hard', topic: 'Exponential Growth',
    question: 'A population grows according to P(t) = 500(1.08)ᵗ, where t is in years. What is the population after 5 years, rounded to the nearest whole number?',
    choices: ['700', '720', '735', '750'], answer: 2,
    explanation: '500 × 1.08⁵ ≈ 500 × 1.4693 ≈ 734.7, which rounds to 735.' },
  { id: 'm-h-37', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'What is the sum of the roots of x² - 8x + 15 = 0?',
    choices: ['5', '7', '8', '15'], answer: 2,
    explanation: 'For ax² + bx + c = 0, the sum of the roots is -b/a = 8. (The roots are 3 and 5.)' },
  { id: 'm-h-38', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'What is the product of the roots of 2x² - 3x - 5 = 0?',
    choices: ['-5/2', '-3/2', '3/2', '5/2'], answer: 0,
    explanation: 'For ax² + bx + c = 0, the product of the roots is c/a = -5/2.' },
  { id: 'm-h-39', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'If h(x) = (x - 3)² - 4, for which value of x does h(x) = 0?',
    choices: ['0', '1', '2', '4'], answer: 1,
    explanation: '(x-3)² = 4 → x - 3 = ±2 → x = 1 or x = 5. Only 1 appears among the choices.' },
  { id: 'm-h-40', subject: 'math', difficulty: 'hard', topic: 'Rational Equations', noCalcEligible: true,
    question: 'Solve for x: (x + 2)/(x - 1) = 4, given x ≠ 1',
    choices: ['1', '2', '3', '4'], answer: 1,
    explanation: 'Cross-multiplying: x + 2 = 4(x - 1) = 4x - 4 → -3x = -6 → x = 2.' },
  { id: 'm-h-41', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'If 3ˣ = 81, what is the value of x?',
    choices: ['2', '3', '4', '5'], answer: 2,
    explanation: '81 = 3⁴, so x = 4.' },
  { id: 'm-h-42', subject: 'math', difficulty: 'hard', topic: 'Function Domain', noCalcEligible: true,
    question: 'What is the domain restriction for f(x) = √(x - 5)?',
    choices: ['x ≥ 5', 'x ≤ 5', 'x > 0', 'x ≠ 5'], answer: 0,
    explanation: 'The expression under a square root must be non-negative: x - 5 ≥ 0, so x ≥ 5.' },
  { id: 'm-h-43', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'If g(x) = 2x² + 4x - 6, what is the x-coordinate of the vertex?',
    choices: ['-2', '-1', '1', '2'], answer: 1,
    explanation: 'The vertex x-coordinate is -b/2a = -4/(2×2) = -1.' },
  { id: 'm-h-44', subject: 'math', difficulty: 'hard', topic: 'Exponents', noCalcEligible: true,
    question: 'Simplify: (2x³y²)(3x²y⁴)',
    choices: ['6x⁵y⁶', '5x⁵y⁶', '6x⁶y⁸', '5x⁶y⁸'], answer: 0,
    explanation: 'Multiply coefficients and add exponents of like bases: 2×3 = 6, x^(3+2) = x⁵, y^(2+4) = y⁶.' },
  { id: 'm-h-45', subject: 'math', difficulty: 'hard', topic: 'Function Domain', noCalcEligible: true,
    question: 'If f(x) = 1/(x - 2), what value of x is NOT in the domain of f?',
    choices: ['0', '1', '2', '3'], answer: 2,
    explanation: 'The denominator cannot equal 0, so x ≠ 2.' },
  { id: 'm-h-46', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'What is the value of x in the equation 5^(x-1) = 125?',
    choices: ['2', '3', '4', '5'], answer: 2,
    explanation: '125 = 5³, so x - 1 = 3, giving x = 4.' },
  { id: 'm-h-47', subject: 'math', difficulty: 'hard', topic: 'Function Transformations', noCalcEligible: true,
    question: 'If the graph of y = x² is reflected over the x-axis and shifted up 3 units, what is the new equation?',
    choices: ['y = -x² + 3', 'y = -x² - 3', 'y = x² + 3', 'y = -(x+3)²'], answer: 0,
    explanation: 'Reflecting over the x-axis negates the function: y = -x². Shifting up 3 adds 3: y = -x² + 3.' },
  { id: 'm-h-48', subject: 'math', difficulty: 'hard', topic: 'Nonlinear Systems', noCalcEligible: true,
    question: 'Solve the system: y = x² and y = 4x - 3. What is one value of x?',
    choices: ['0', '1', '2', '4'], answer: 1,
    explanation: 'Setting equal: x² = 4x - 3 → x² - 4x + 3 = 0 → (x-1)(x-3) = 0, so x = 1 or x = 3. Only 1 appears among the choices.' },
  { id: 'm-h-49', subject: 'math', difficulty: 'hard', topic: 'Composite Functions', noCalcEligible: true,
    question: 'If a(x) = x³ and b(x) = x - 1, what is a(b(2))?',
    choices: ['0', '1', '2', '8'], answer: 1,
    explanation: 'b(2) = 2 - 1 = 1. Then a(1) = 1³ = 1.' },
  { id: 'm-h-50', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'What is the value of x that satisfies 4ˣ = 8^(x-1)?',
    choices: ['1', '2', '3', '4'], answer: 2,
    explanation: 'Rewrite with base 2: 2^(2x) = 2^(3(x-1)) → 2x = 3x - 3 → x = 3.' },
  { id: 'm-h-51', subject: 'math', difficulty: 'hard', topic: 'Absolute Value Inequalities', noCalcEligible: true,
    question: 'Which value of x satisfies |2x + 1| < 9?',
    choices: ['-6', '-5', '0', '5'], answer: 2,
    explanation: '-9 < 2x + 1 < 9 simplifies to -5 < x < 4. Only 0 falls strictly within that range.' },
  { id: 'm-h-52', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'What is the axis of symmetry of the parabola y = 2x² - 12x + 7?',
    choices: ['x = 2', 'x = 3', 'x = 4', 'x = 6'], answer: 1,
    explanation: 'Axis of symmetry: x = -b/2a = 12/(2×2) = 3.' },
  { id: 'm-h-53', subject: 'math', difficulty: 'hard', topic: 'Function Transformations', noCalcEligible: true,
    question: 'If f(x) = x² is stretched vertically by a factor of 3 and shifted left 2 units, what is the new function?',
    choices: ['3(x+2)²', '3(x-2)²', '(3x+2)²', '3x² + 2'], answer: 0,
    explanation: 'A vertical stretch by 3 multiplies the output by 3; a shift left 2 replaces x with (x+2): g(x) = 3(x+2)².' },
  { id: 'm-h-54', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'Solve for x: 2^(x+1) = 4^(x-1)',
    choices: ['2', '3', '4', '5'], answer: 1,
    explanation: 'Rewrite with base 2: 2^(x+1) = 2^(2(x-1)) → x + 1 = 2x - 2 → x = 3.' },
  { id: 'm-h-55', subject: 'math', difficulty: 'hard', topic: 'Remainder Theorem', noCalcEligible: true,
    question: 'What is the remainder when x³ + 2x² - x + 5 is divided by (x + 1)?',
    choices: ['3', '5', '7', '9'], answer: 2,
    explanation: 'By the remainder theorem, substitute x = -1: (-1) + 2 + 1 + 5 = 7.' },
  { id: 'm-h-56', subject: 'math', difficulty: 'hard', topic: 'Discriminant', noCalcEligible: true,
    question: 'If the discriminant of a quadratic equation is negative, how many real solutions does the equation have?',
    choices: ['0', '1', '2', 'infinitely many'], answer: 0,
    explanation: 'A negative discriminant (b² - 4ac < 0) means the quadratic has no real solutions.' },
  { id: 'm-h-57', subject: 'math', difficulty: 'hard', topic: 'Logarithms', noCalcEligible: true,
    question: 'What is the value of x if log₃(x) = 4?',
    choices: ['12', '27', '64', '81'], answer: 3,
    explanation: 'log₃(x) = 4 means x = 3⁴ = 81.' },
  { id: 'm-h-58', subject: 'math', difficulty: 'hard', topic: 'Function Domain', noCalcEligible: true,
    question: 'If f(x) = √x and g(x) = x - 4, what is the domain of f(g(x))?',
    choices: ['x ≥ 0', 'x ≥ 4', 'x ≤ 4', 'x ≠ 4'], answer: 1,
    explanation: 'f(g(x)) = √(x - 4), which requires x - 4 ≥ 0, so x ≥ 4.' },
  { id: 'm-h-59', subject: 'math', difficulty: 'hard', topic: 'Inverse Functions', noCalcEligible: true,
    question: 'If f(x) = 2x - 5, what is f⁻¹(x)?',
    choices: ['(x+5)/2', '(x-5)/2', '2x+5', '(x/2)+5'], answer: 0,
    explanation: 'Let y = 2x - 5. Swap x and y: x = 2y - 5. Solving for y: y = (x+5)/2.' },
  { id: 'm-h-60', subject: 'math', difficulty: 'hard', topic: 'Inverse Functions', noCalcEligible: true,
    question: 'What is the inverse of f(x) = x³ + 2?',
    choices: ['∛(x-2)', '∛(x+2)', 'x³-2', '(x-2)³'], answer: 0,
    explanation: 'Let y = x³ + 2. Swap x and y: x = y³ + 2 → y³ = x - 2 → y = ∛(x-2).' },
  { id: 'm-h-61', subject: 'math', difficulty: 'hard', topic: 'Absolute Value', noCalcEligible: true,
    question: 'If f(x) = |x - 3|, what is f(-2)?',
    choices: ['1', '3', '5', '7'], answer: 2,
    explanation: 'f(-2) = |-2 - 3| = |-5| = 5.' },
  { id: 'm-h-62', subject: 'math', difficulty: 'hard', topic: 'Piecewise Functions', noCalcEligible: true,
    question: 'For the piecewise function f(x) = x² if x < 0, and f(x) = 2x + 1 if x ≥ 0, what is f(-3)?',
    choices: ['5', '7', '9', '11'], answer: 2,
    explanation: 'Since -3 < 0, use f(x) = x²: f(-3) = (-3)² = 9.' },
  { id: 'm-h-63', subject: 'math', difficulty: 'hard', topic: 'Discriminant', noCalcEligible: true,
    question: 'How many x-intercepts does the graph of f(x) = x² - 6x + 9 have?',
    choices: ['0', '1', '2', 'infinitely many'], answer: 1,
    explanation: 'x² - 6x + 9 = (x-3)², a perfect square with discriminant 0, so the parabola touches the x-axis at exactly one point.' },
  { id: 'm-h-64', subject: 'math', difficulty: 'hard', topic: 'Circle Equations', noCalcEligible: true,
    question: 'What is the equation of a circle with center (0, 0) and radius 6?',
    choices: ['x² + y² = 6', 'x² + y² = 36', 'x² + y² = 12', '(x-6)² + y² = 36'], answer: 1,
    explanation: 'The equation is x² + y² = r², and r² = 6² = 36.' },
  { id: 'm-h-65', subject: 'math', difficulty: 'hard', topic: 'Radicals', noCalcEligible: true,
    question: 'Simplify: √50',
    choices: ['5√2', '10√5', '25√2', '2√5'], answer: 0,
    explanation: '√50 = √(25 × 2) = 5√2.' },
  { id: 'm-h-66', subject: 'math', difficulty: 'hard', topic: 'Radicals', noCalcEligible: true,
    question: 'Rationalize the denominator: 1/√3',
    choices: ['√3/3', '1/3', '3/√3', '√3'], answer: 0,
    explanation: 'Multiply numerator and denominator by √3: (1×√3)/(√3×√3) = √3/3.' },
  { id: 'm-h-67', subject: 'math', difficulty: 'hard', topic: 'Exponential Functions', noCalcEligible: true,
    question: 'If f(x) = 2ˣ, what is f(0) + f(1) + f(2)?',
    choices: ['5', '6', '7', '8'], answer: 2,
    explanation: 'f(0) + f(1) + f(2) = 1 + 2 + 4 = 7.' },
  { id: 'm-h-68', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'What is the value of x if 9ˣ = 27^(x-1)?',
    choices: ['1', '2', '3', '4'], answer: 2,
    explanation: 'Rewrite with base 3: 3^(2x) = 3^(3(x-1)) → 2x = 3x - 3 → x = 3.' },
  { id: 'm-h-69', subject: 'math', difficulty: 'hard', topic: 'Function Behavior',
    question: 'Which type of function characteristically has a horizontal asymptote?',
    choices: ['linear function', 'quadratic function', 'exponential function', 'cubic function'], answer: 2,
    explanation: 'Exponential functions (like decay functions) level off toward a constant value, creating a horizontal asymptote; linear, quadratic, and cubic functions do not.' },
  { id: 'm-h-70', subject: 'math', difficulty: 'hard', topic: 'Rational Exponents', noCalcEligible: true,
    question: 'What is the value of 27^(2/3)?',
    choices: ['6', '9', '18', '81'], answer: 1,
    explanation: '27^(1/3) = 3, and 3² = 9.' },
  { id: 'm-h-71', subject: 'math', difficulty: 'hard', topic: 'Composite Functions', noCalcEligible: true,
    question: 'If f(x) = 4x² and g(x) = f(x)/4, what is g(3)?',
    choices: ['6', '9', '12', '16'], answer: 1,
    explanation: 'f(3) = 4(9) = 36. g(3) = 36/4 = 9.' },
  { id: 'm-h-72', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'Solve for x: x² + 6x + 9 = 0',
    choices: ['-3', '-1', '1', '3'], answer: 0,
    explanation: 'x² + 6x + 9 = (x+3)², so the equation has a double root at x = -3.' },
  { id: 'm-h-73', subject: 'math', difficulty: 'hard', topic: 'Rational Expressions', noCalcEligible: true,
    question: 'What value of x, other than x = 5, makes the expression (x-5)/(x²-25) undefined?',
    choices: ['-5', '-1', '1', '5'], answer: 0,
    explanation: 'x² - 25 = (x-5)(x+5) = 0 when x = 5 or x = -5. The other value is x = -5.' },
  { id: 'm-h-74', subject: 'math', difficulty: 'hard', topic: 'Function Domain', noCalcEligible: true,
    question: 'If f(x) = √(9 - x²), what is the domain of f?',
    choices: ['-3 ≤ x ≤ 3', 'x ≥ 3', 'x ≤ -3', 'all real numbers'], answer: 0,
    explanation: 'The expression under the square root must be non-negative: 9 - x² ≥ 0, which gives -3 ≤ x ≤ 3.' },
  { id: 'm-h-75', subject: 'math', difficulty: 'hard', topic: 'Logarithms', noCalcEligible: true,
    question: 'What is the value of log₅(1)?',
    choices: ['0', '1', '5', 'undefined'], answer: 0,
    explanation: 'For any valid base b, log_b(1) = 0, since b⁰ = 1.' },
  { id: 'm-h-76', subject: 'math', difficulty: 'hard', topic: 'Function Transformations', noCalcEligible: true,
    question: 'If the graph of f(x) = x² is shifted right 4 units and reflected over the x-axis, what is the new equation?',
    choices: ['-(x-4)²', '-(x+4)²', '(x-4)²-1', '-x²-4'], answer: 0,
    explanation: 'Shifting right 4 replaces x with (x-4); reflecting over the x-axis negates the result: g(x) = -(x-4)².' },
  { id: 'm-h-77', subject: 'math', difficulty: 'hard', topic: 'Sequences',
    question: 'What is the sum of the infinite geometric series 4 + 2 + 1 + 0.5 + ...?',
    choices: ['6', '7', '8', '16'], answer: 2,
    explanation: 'a₁ = 4, r = 0.5. Sum = a₁/(1-r) = 4/0.5 = 8.' },
  { id: 'm-h-78', subject: 'math', difficulty: 'hard', topic: 'Sequences', noCalcEligible: true,
    question: 'If the nth term of a sequence is aₙ = 3n - 2, what is the 10th term?',
    choices: ['25', '26', '28', '30'], answer: 2,
    explanation: 'a₁₀ = 3(10) - 2 = 28.' },
  { id: 'm-h-79', subject: 'math', difficulty: 'hard', topic: 'Exponential Equations', noCalcEligible: true,
    question: 'What is the value of x in the equation (1/2)ˣ = 8?',
    choices: ['-3', '-2', '2', '3'], answer: 0,
    explanation: '8 = 2³ = (1/2)⁻³, so x = -3.' },
  { id: 'm-h-80', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'If f(x) = x² - 4x, what is the minimum value of f(x)?',
    choices: ['-8', '-4', '0', '4'], answer: 1,
    explanation: 'Completing the square: f(x) = (x-2)² - 4. The minimum value is -4, occurring at x = 2.' },
  { id: 'm-h-81', subject: 'math', difficulty: 'hard', topic: 'Coordinate Geometry', noCalcEligible: true,
    question: 'What is the equation of the line perpendicular to y = 2x + 3 that passes through (0, 1)?',
    choices: ['y = -1/2x + 1', 'y = 2x + 1', 'y = 1/2x + 1', 'y = -2x + 1'], answer: 0,
    explanation: 'A perpendicular line has a slope that is the negative reciprocal: -1/2. With y-intercept 1: y = -1/2x + 1.' },
  { id: 'm-h-82', subject: 'math', difficulty: 'hard', topic: 'Rational Exponents', noCalcEligible: true,
    question: 'Simplify: (x^(1/2))(x^(1/3))',
    choices: ['x^(5/6)', 'x^(1/6)', 'x^(2/5)', 'x¹'], answer: 0,
    explanation: 'Add exponents: 1/2 + 1/3 = 5/6, so the result is x^(5/6).' },
  { id: 'm-h-83', subject: 'math', difficulty: 'hard', topic: 'Composite Functions', noCalcEligible: true,
    question: 'If f(x) = x² and g(x) = √x, what is g(f(3))?',
    choices: ['3', '6', '9', '81'], answer: 0,
    explanation: 'f(3) = 9. g(9) = √9 = 3.' },
  { id: 'm-h-84', subject: 'math', difficulty: 'hard', topic: 'Discriminant', noCalcEligible: true,
    question: 'What is the discriminant of 3x² - 4x + 2 = 0?',
    choices: ['-8', '-4', '8', '16'], answer: 0,
    explanation: 'Discriminant = b² - 4ac = (-4)² - 4(3)(2) = 16 - 24 = -8.' },
  { id: 'm-h-85', subject: 'math', difficulty: 'hard', topic: 'Inverse Functions', noCalcEligible: true,
    question: 'If h(x) = 5 - x² for x ≥ 0, what is h⁻¹(x)?',
    choices: ['√(5-x)', '5-√x', '√(x-5)', '(5-x)²'], answer: 0,
    explanation: 'Let y = 5 - x². Solving for x: x² = 5 - y → x = √(5-y) (positive root, since x ≥ 0). So h⁻¹(x) = √(5-x).' },
  { id: 'm-h-86', subject: 'math', difficulty: 'hard', topic: 'Quadratics', noCalcEligible: true,
    question: 'Which value of x satisfies 2x² = 32?',
    choices: ['-4', '-2', '2', '3'], answer: 0,
    explanation: 'x² = 16, so x = ±4. Only -4 appears among the choices.' },
  { id: 'm-h-87', subject: 'math', difficulty: 'hard', topic: 'Quadratics',
    question: "A rectangle's length is x + 4 and width is x. If its area is 45, what is the value of x?",
    choices: ['3', '4', '5', '6'], answer: 2,
    explanation: 'x(x+4) = 45 → x² + 4x - 45 = 0 → (x+9)(x-5) = 0. Since x must be positive, x = 5.' },
  { id: 'm-h-88', subject: 'math', difficulty: 'hard', topic: 'Coordinate Geometry', noCalcEligible: true,
    question: 'What is the value of b if the line y = bx + 2 is parallel to the line 3x - y = 7?',
    choices: ['-3', '1/3', '2', '3'], answer: 3,
    explanation: 'Rewriting 3x - y = 7 as y = 3x - 7 shows a slope of 3. Parallel lines share the same slope, so b = 3.' },

  // ---------------- ENGLISH · EASY ----------------
  { id: 'e-e-1', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct verb: 'The group of students ___ excited about the field trip.'",
    choices: ['is', 'are', 'were', 'be'], answer: 0,
    explanation: "'Group' is a singular collective noun, so it takes the singular verb 'is'." },
  { id: 'e-e-2', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence is punctuated correctly?',
    choices: ['I bought apples, oranges, and bananas.', 'I bought apples oranges, and bananas.', 'I bought, apples oranges and bananas.', 'I bought apples, oranges and, bananas.'], answer: 0,
    explanation: 'A comma is needed after each item in a list of three or more, including before the conjunction (the Oxford comma).' },
  { id: 'e-e-3', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'meticulous' most nearly means:",
    choices: ['careless', 'careful', 'quick', 'loud'], answer: 1,
    explanation: "'Meticulous' means showing great attention to detail; the closest synonym is 'careful'." },
  { id: 'e-e-4', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Every student must bring ___ own laptop.",
    choices: ['their', 'his or her', "they're", 'our'], answer: 1,
    explanation: "'Every student' is singular, so the traditionally correct formal pronoun is 'his or her'." },
  { id: 'e-e-5', subject: 'english', difficulty: 'easy', topic: 'Sentence Structure',
    question: 'Which is a complete sentence?',
    choices: ['Running through the park.', 'She runs through the park every morning.', 'Because she likes to run.', 'The park where she runs.'], answer: 1,
    explanation: 'Only this option has a subject and a verb forming a complete, independent thought.' },
  { id: 'e-e-6', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence uses the apostrophe correctly?',
    choices: ['The cats toy was torn.', "The cat's toy was torn.", "The cats' toy's was torn.", "The cats toys' was torn."], answer: 1,
    explanation: "A single cat possessing one toy takes an apostrophe + s: 'cat's'." },
  { id: 'e-e-7', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'reluctant' most nearly means:",
    choices: ['eager', 'unwilling', 'curious', 'angry'], answer: 1,
    explanation: "'Reluctant' means hesitant or unwilling to do something." },
  { id: 'e-e-8', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence correctly uses a comma?',
    choices: ['After the movie we went to dinner.', 'After the movie, we went to dinner.', 'After, the movie we went to dinner.', 'After the movie we, went to dinner.'], answer: 1,
    explanation: 'A comma follows an introductory phrase before the main clause begins.' },
  { id: 'e-e-9', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Choose the correct verb: \'Neither of the answers ___ correct.\'',
    choices: ['is', 'are', 'were', 'be'], answer: 0,
    explanation: "'Neither' is singular, so it takes the singular verb 'is.'" },
  { id: 'e-e-10', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Which sentence is grammatically correct?',
    choices: ['Me and him went to the store.', 'He and I went to the store.', 'Him and me went to the store.', 'I and he went to the store.'], answer: 1,
    explanation: "Subject pronouns 'he' and 'I' are correct as the subject of the sentence, in the conventional order." },
  { id: 'e-e-11', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'ancient' most nearly means:",
    choices: ['modern', 'old', 'new', 'temporary'], answer: 1,
    explanation: "'Ancient' means very old, belonging to the distant past." },
  { id: 'e-e-12', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Which sentence uses correct subject-verb agreement?',
    choices: ['The list of items are on the table.', 'The list of items is on the table.', 'The list of items were on the table.', 'The list of items be on the table.'], answer: 1,
    explanation: "The subject is 'list' (singular), not 'items,' so the singular verb 'is' is correct." },
  { id: 'e-e-13', subject: 'english', difficulty: 'easy', topic: 'Spelling',
    question: 'Choose the correctly spelled word.',
    choices: ['recieve', 'receive', 'receeve', 'receve'], answer: 1,
    explanation: "The correct spelling follows 'i before e except after c': receive." },
  { id: 'e-e-14', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence correctly punctuates a direct quotation?',
    choices: ['She said I will be there soon.', 'She said, "I will be there soon."', 'She said "I will be there soon."', 'She said, I will be there soon.'], answer: 1,
    explanation: 'A comma introduces the quotation, and quotation marks enclose the exact words spoken.' },
  { id: 'e-e-15', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'generous' most nearly means:",
    choices: ['stingy', 'giving', 'cruel', 'timid'], answer: 1,
    explanation: "'Generous' describes someone willing to give freely." },
  { id: 'e-e-16', subject: 'english', difficulty: 'easy', topic: 'Sentence Structure',
    question: 'Which sentence is a complete, correctly punctuated sentence?',
    choices: ['Although she was tired.', 'She was tired, but she kept working.', 'She was tired but kept, working.', 'Tired she kept working, although.'], answer: 1,
    explanation: 'This option joins two independent clauses correctly with a comma and coordinating conjunction.' },
  { id: 'e-e-17', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct pronoun: 'Give the book to ___.'",
    choices: ['I', 'me', 'myself', 'mine'], answer: 1,
    explanation: "'Me' is the correct object pronoun following the preposition 'to.'" },
  { id: 'e-e-18', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Which word correctly completes the sentence? 'The weather today is ___ than yesterday.'",
    choices: ['colder', 'more colder', 'most cold', 'coldest'], answer: 0,
    explanation: "'Colder' is the correct comparative form; 'more colder' is redundant." },
  { id: 'e-e-19', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct verb: 'Each of the boys ___ his own bicycle.'",
    choices: ['have', 'has', 'having', 'had'], answer: 1,
    explanation: "'Each' is singular, so it takes the singular verb 'has.'" },
  { id: 'e-e-20', subject: 'english', difficulty: 'easy', topic: 'Capitalization',
    question: 'Which sentence uses correct capitalization?',
    choices: ['We visited Paris in the Summer.', 'We visited Paris in the summer.', 'we visited paris in the summer.', 'We Visited Paris In The Summer.'], answer: 1,
    explanation: "'Summer' is a common noun (a season) and should not be capitalized; 'Paris' is a proper noun and is correctly capitalized." },
  { id: 'e-e-21', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'brief' most nearly means:",
    choices: ['lengthy', 'short', 'boring', 'detailed'], answer: 1,
    explanation: "'Brief' means short in duration or length." },
  { id: 'e-e-22', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Which sentence is punctuated correctly?',
    choices: ["Its a beautiful day.", "It's a beautiful day.", "Its' a beautiful day.", "It is' a beautiful day."], answer: 1,
    explanation: "The contraction 'it's' (meaning 'it is') requires an apostrophe." },
  { id: 'e-e-23', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct plural form: 'The ___ were all lined up on the shelf.'",
    choices: ['box', 'boxs', 'boxes', 'boxies'], answer: 2,
    explanation: "Nouns ending in 'x' form the plural by adding 'es': boxes." },
  { id: 'e-e-24', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: 'Which sentence is grammatically correct?',
    choices: ["She don't like coffee.", "She doesn't like coffee.", "She not like coffee.", "She isn't likes coffee."], answer: 1,
    explanation: "The singular subject 'she' requires 'doesn't,' not 'don't.'" },
  { id: 'e-e-25', subject: 'english', difficulty: 'easy', topic: 'Vocabulary',
    question: "The word 'assist' most nearly means:",
    choices: ['hinder', 'help', 'ignore', 'avoid'], answer: 1,
    explanation: "'Assist' means to help or support." },
  { id: 'e-e-26', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Which sentence uses the correct form of 'there,' 'their,' or 'they're'?",
    choices: ['Their going to the park.', 'There going to the park.', "They're going to the park.", "Ther're going to the park."], answer: 2,
    explanation: "'They're' is the contraction of 'they are,' which fits the sentence." },
  { id: 'e-e-27', subject: 'english', difficulty: 'easy', topic: 'Grammar',
    question: "Choose the correct word: 'She is taller ___ her brother.'",
    choices: ['then', 'than', 'that', 'this'], answer: 1,
    explanation: "'Than' is used for comparisons; 'then' refers to time or sequence." },
  { id: 'e-e-28', subject: 'english', difficulty: 'easy', topic: 'Punctuation',
    question: 'Which sentence correctly uses a semicolon?',
    choices: ['I love reading; especially mystery novels.', 'I love reading; I especially enjoy mystery novels.', 'I love reading, I especially enjoy mystery novels;', 'I love reading; and mystery novels.'], answer: 1,
    explanation: 'A semicolon correctly joins two independent clauses without a conjunction.' },

  // ---------------- ENGLISH · MEDIUM ----------------
  { id: 'e-m-1', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The team practiced for months; ___, they lost the championship game.',
    choices: ['therefore', 'however', 'moreover', 'for example'], answer: 1,
    explanation: "'However' signals the contrast between practicing hard and still losing." },
  { id: 'e-m-2', subject: 'english', difficulty: 'medium', topic: 'Parallelism',
    question: 'Which sentence demonstrates correct parallel structure?',
    choices: ['She likes swimming, biking, and to run.', 'She likes swimming, biking, and running.', 'She likes to swim, biking, and running.', 'She likes to swim, to bike, and running.'], answer: 1,
    explanation: 'All three items in the list should share the same grammatical form: swimming, biking, running.' },
  { id: 'e-m-3', subject: 'english', difficulty: 'medium', topic: 'Modifiers',
    question: 'Which sentence avoids a dangling modifier?',
    choices: ['Walking to school, the rain began to fall.', 'Walking to school, I got caught in the rain.', 'The rain, walking to school, began to fall.', 'Walking to school the rain fell on me.'], answer: 1,
    explanation: "The introductory phrase 'walking to school' must describe the subject that follows it — here, 'I', not the rain." },
  { id: 'e-m-4', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Although solar panels have become significantly cheaper over the past decade, many homeowners still hesitate to install them, citing the high upfront cost as a barrier despite long-term savings on energy bills." According to the passage, why do many homeowners hesitate to install solar panels?',
    choices: ["They don't believe solar panels save money.", 'The upfront cost concerns them despite long-term savings.', 'Solar panels have become more expensive.', 'They are unaware solar panels exist.'], answer: 1,
    explanation: 'The passage states the high upfront cost is the barrier, even though there are long-term savings.' },
  { id: 'e-m-5', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The bridge was closed for repairs; ___, commuters had to take a longer route to work.',
    choices: ['similarly', 'as a result', 'in contrast', 'for instance'], answer: 1,
    explanation: "'As a result' correctly shows the closure caused the longer commute." },
  { id: 'e-m-6', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which word best completes the sentence in a formal tone? 'The committee's decision was ___ by all members present.'",
    choices: ['okayed', 'approved', 'given thumbs up', 'agreed to sorta'], answer: 1,
    explanation: "'Approved' is the formal, precise word choice appropriate for the context." },
  { id: 'e-m-7', subject: 'english', difficulty: 'medium', topic: 'Verb Tense',
    question: 'Which sentence has consistent verb tense?',
    choices: ['She finished her homework and goes to bed.', 'She finishes her homework and went to bed.', 'She finished her homework and went to bed.', 'She finish her homework and went to bed.'], answer: 2,
    explanation: 'Both verbs should be in the same (past) tense: finished, went.' },
  { id: 'e-m-8', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Despite initial skepticism from critics, the museum\'s new exhibit on ancient trade routes has drawn record crowds, suggesting that public interest in history may be stronger than experts previously assumed." What can be inferred from the passage?',
    choices: ['Critics were correct that the exhibit would fail.', 'Public interest in history might be greater than experts thought.', 'The museum plans to close the exhibit early.', 'Ancient trade routes are no longer a popular topic.'], answer: 1,
    explanation: 'The record crowds despite skepticism suggest public interest exceeded expert expectations.' },
  { id: 'e-m-9', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The experiment produced unexpected results; ___, the researchers decided to repeat it under stricter conditions.',
    choices: ['consequently', 'meanwhile', 'in addition', 'on the other hand'], answer: 0,
    explanation: "'Consequently' correctly shows that the unexpected results led directly to the decision to repeat the experiment." },
  { id: 'e-m-10', subject: 'english', difficulty: 'medium', topic: 'Parallelism',
    question: 'Which sentence is parallel?',
    choices: ['The coach asked the players to run faster, jump higher, and to be more focused.', 'The coach asked the players to run faster, jump higher, and focus more.', 'The coach asked the players running faster, jumping higher, and to focus more.', 'The coach asked the players to running faster, jump higher, and focus more.'], answer: 1,
    explanation: "All three verbs following 'to' should share the same infinitive form: run, jump, focus." },
  { id: 'e-m-11', subject: 'english', difficulty: 'medium', topic: 'Modifiers',
    question: 'Which sentence correctly places the modifier to convey that she was the only person to answer correctly?',
    choices: ['Only she answered the question correctly.', 'She only answered the question correctly.', 'She answered only the question correctly.', 'She answered the question only correctly.'], answer: 0,
    explanation: "Placing 'only' directly before 'she' correctly conveys that she alone answered correctly." },
  { id: 'e-m-12', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "While many assume that a larger vocabulary is the primary driver of strong writing, experienced editors often note that clarity and sentence rhythm matter more than word choice alone." According to the passage, experienced editors believe that:',
    choices: ['vocabulary size is irrelevant to writing quality.', 'clarity and rhythm are more important than vocabulary alone.', 'larger vocabularies always produce clearer writing.', 'sentence rhythm has no effect on writing quality.'], answer: 1,
    explanation: 'The passage states editors believe clarity and rhythm "matter more than word choice alone," not that vocabulary is irrelevant.' },
  { id: 'e-m-13', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which word best fits in a formal essay? 'The results of the study were ___ significant.'",
    choices: ['kinda', 'statistically', 'super', 'sort of'], answer: 1,
    explanation: "'Statistically' is the precise, formal term used to describe significance in research contexts." },
  { id: 'e-m-14', subject: 'english', difficulty: 'medium', topic: 'Verb Tense',
    question: 'Which sentence maintains correct and consistent verb tense?',
    choices: ['By the time she arrived, the meeting had already started.', 'By the time she arrives, the meeting had already started.', 'By the time she arrived, the meeting has already started.', 'By the time she arrive, the meeting started.'], answer: 0,
    explanation: "The past perfect 'had started' correctly shows an action completed before another past action ('arrived')." },
  { id: 'e-m-15', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: "The company's profits declined sharply; ___, it announced a hiring freeze.",
    choices: ['as a result', 'similarly', 'for instance', 'nonetheless'], answer: 0,
    explanation: "'As a result' correctly shows the profit decline caused the hiring freeze." },
  { id: 'e-m-16', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Urban planners increasingly favor mixed-use developments, which combine residential, commercial, and recreational spaces within a single area, arguing that such designs reduce commute times and foster community interaction." According to the passage, urban planners favor mixed-use developments because they:',
    choices: ['increase the cost of housing.', 'reduce commute times and encourage community interaction.', 'separate residential and commercial spaces more clearly.', 'eliminate the need for public transportation.'], answer: 1,
    explanation: 'The passage directly states these designs "reduce commute times and foster community interaction."' },
  { id: 'e-m-17', subject: 'english', difficulty: 'medium', topic: 'Punctuation',
    question: 'Which sentence is correctly punctuated?',
    choices: ['My favorite subjects are, math, science, and history.', 'My favorite subjects are math, science, and history.', 'My favorite subjects, are math, science, and history.', 'My favorite subjects are math science, and history.'], answer: 1,
    explanation: 'No comma should separate a verb from its list of objects; commas are only needed between list items.' },
  { id: 'e-m-18', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which revision best improves the formality of the sentence 'The manager said the deal was a done deal'?",
    choices: ['The manager said the deal was totally finished.', 'The manager confirmed that the agreement was finalized.', 'The manager said the deal was, like, done.', 'The manager said the deal was wrapped up.'], answer: 1,
    explanation: "'Confirmed' and 'finalized' are precise, formal word choices appropriate for professional writing." },
  { id: 'e-m-19', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The city invested heavily in public transit; ___, traffic congestion decreased significantly.',
    choices: ['however', 'as a result', 'in contrast', 'for example'], answer: 1,
    explanation: "'As a result' correctly shows that the investment caused the decrease in congestion." },
  { id: 'e-m-20', subject: 'english', difficulty: 'medium', topic: 'Parallelism',
    question: 'Which sentence is parallel?',
    choices: ['The report was clear, concise, and had good organization.', 'The report was clear, concise, and well-organized.', 'The report was clear, being concise, and well-organized.', 'The report was clarity, concise, and well-organized.'], answer: 1,
    explanation: 'All three descriptors should share the same adjective form: clear, concise, well-organized.' },
  { id: 'e-m-21', subject: 'english', difficulty: 'medium', topic: 'Modifiers',
    question: 'Which sentence avoids a dangling modifier?',
    choices: ['Having finished the exam, the room felt quiet.', 'Having finished the exam, she left the room quietly.', 'The room, having finished the exam, felt quiet.', 'Having finished the exam the room was quiet.'], answer: 1,
    explanation: "The phrase 'having finished the exam' must describe the subject that follows it — 'she,' not the room." },
  { id: 'e-m-22', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: 'Passage: "Although remote work has increased flexibility for many employees, some managers report that collaboration and spontaneous problem-solving have become more difficult without in-person interaction." According to the passage, some managers believe remote work has made which aspect of teamwork more challenging?',
    choices: ['employee flexibility.', 'collaboration and spontaneous problem-solving.', 'employee satisfaction.', 'salary negotiations.'], answer: 1,
    explanation: 'The passage directly states that managers find "collaboration and spontaneous problem-solving" more difficult remotely.' },
  { id: 'e-m-23', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which word best completes the sentence formally? 'The board will ___ the proposal at next week's meeting.'",
    choices: ['check out', 'review', 'look over', 'go through'], answer: 1,
    explanation: "'Review' is the precise, formal verb choice appropriate for a board meeting." },
  { id: 'e-m-24', subject: 'english', difficulty: 'medium', topic: 'Verb Tense',
    question: 'Which sentence has consistent verb tense?',
    choices: ['He studies all night and passed the exam.', 'He studied all night and passes the exam.', 'He studied all night and passed the exam.', 'He study all night and passed the exam.'], answer: 2,
    explanation: 'Both verbs should be in the past tense: studied, passed.' },
  { id: 'e-m-25', subject: 'english', difficulty: 'medium', topic: 'Transitions',
    question: 'The novel received mixed reviews from critics; ___, it became a bestseller.',
    choices: ['nevertheless', 'similarly', 'therefore', 'additionally'], answer: 0,
    explanation: "'Nevertheless' signals the contrast between mixed reviews and commercial success." },
  { id: 'e-m-26', subject: 'english', difficulty: 'medium', topic: 'Reading Comprehension',
    question: "Passage: \"Despite the rise of digital music streaming, vinyl record sales have grown steadily over the past decade, driven largely by collectors and audiophiles who value the format's tangible and nostalgic qualities.\" According to the passage, the growth in vinyl sales is primarily driven by:",
    choices: ['declining streaming quality.', "collectors and audiophiles who value its tangible, nostalgic appeal.", 'a complete replacement of digital music.', 'lower production costs.'], answer: 1,
    explanation: 'The passage states growth is "driven largely by collectors and audiophiles" who value those qualities.' },
  { id: 'e-m-27', subject: 'english', difficulty: 'medium', topic: 'Punctuation',
    question: 'Which sentence correctly uses a colon?',
    choices: ['She packed the essentials: a tent, sleeping bag, and flashlight.', 'She packed the essentials, a tent, sleeping bag, and flashlight.', 'She packed the: essentials, a tent, sleeping bag, and flashlight.', 'She packed the essentials a tent, sleeping bag, and flashlight.'], answer: 0,
    explanation: 'A colon correctly introduces a list following a complete independent clause.' },
  { id: 'e-m-28', subject: 'english', difficulty: 'medium', topic: 'Word Choice',
    question: "Which word best completes the sentence? 'The committee's findings were ___ by independent researchers.'",
    choices: ['double-checked', 'corroborated', 'looked at', 'backed up'], answer: 1,
    explanation: "'Corroborated' is the precise, formal term for findings being confirmed by independent sources." },

  // ---------------- ENGLISH · HARD ----------------
  { id: 'e-h-1', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "Though the committee's report was ostensibly balanced, careful readers detected a subtle bias that rendered its conclusions ___.",
    choices: ['unimpeachable', 'tendentious', 'exhaustive', 'redundant'], answer: 1,
    explanation: "'Tendentious' means promoting a particular, biased point of view — matching the 'subtle bias' described despite the report's apparent balance." },
  { id: 'e-h-2', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: 'Which sentence correctly uses the subjunctive mood?',
    choices: ['If I was rich, I would travel the world.', 'If I were rich, I would travel the world.', 'If I am rich, I would travel the world.', 'If I will be rich, I would travel the world.'], answer: 1,
    explanation: "The subjunctive mood for hypothetical conditions uses 'were' regardless of subject: 'If I were rich...'" },
  { id: 'e-h-3', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: "A student is writing a report and wants to emphasize a contrast between two studies' findings. Which transition should be used?",
    choices: ['additionally', 'similarly', 'conversely', 'consequently'], answer: 2,
    explanation: "'Conversely' signals a direct contrast between two ideas." },
  { id: 'e-h-4', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: 'Passage: "The novelist\'s early works were dismissed by critics at the time as derivative pastiches of more established authors, their apparent debts to prior literary traditions overshadowing, in the critics\' eyes, any originality; yet a close reading — attentive to the era\'s narrow critical vocabulary for innovation — reveals subtle structural experiments that would later influence an entire generation of writers, suggesting the initial dismissal reflected the limits of contemporary criticism more than the works themselves." The passage suggests that the initial critical dismissal of the novelist\'s early works primarily reflected:',
    choices: ["a deliberate campaign to suppress the novelist's career.", "limitations in the critical standards of the time rather than the works' actual quality.", 'accurate judgments that were later reversed for sentimental reasons.', "the novelist's own dissatisfaction with the work."], answer: 1,
    explanation: 'The passage states the dismissal "reflected the limits of contemporary criticism more than the works themselves" — the critics\' narrow standards, not the writing itself, were the issue.' },
  { id: 'e-h-5', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The politician's speech was criticized as ___, full of vague promises but no concrete plans.",
    choices: ['substantive', 'platitudinous', 'meticulous', 'concise'], answer: 1,
    explanation: "'Platitudinous' means full of empty, overused statements — matching 'vague promises but no concrete plans.'" },
  { id: 'e-h-6', subject: 'english', difficulty: 'hard', topic: 'Modifiers',
    question: 'Which sentence is free of a misplaced modifier?',
    choices: ['The professor discussed the theory in the lecture that was widely debated.', 'The professor discussed, in the lecture, the theory that was widely debated.', 'In the lecture, the professor discussed the theory that was widely debated.', 'The theory, the professor discussed in the lecture widely debated.'], answer: 2,
    explanation: "Placing 'in the lecture' clearly at the start avoids ambiguity about what was 'widely debated' — the theory, not the lecture." },
  { id: 'e-h-7', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: 'A writer wants to cite a statistic to support the claim that renewable energy adoption is accelerating. Which sentence best achieves this goal?',
    choices: ['Renewable energy is good for the environment.', 'According to a 2024 report, global solar capacity increased by 35% in a single year.', 'Many people like renewable energy.', 'Renewable energy has existed for decades.'], answer: 1,
    explanation: 'Only this option provides a specific, cited statistic supporting the claim of accelerating adoption.' },
  { id: 'e-h-8', subject: 'english', difficulty: 'hard', topic: 'Parallelism',
    question: 'Which sentence correctly uses parallel structure with correlative conjunctions?',
    choices: ['She not only enjoys reading but also to write.', 'She not only enjoys reading but also enjoys writing.', 'Not only she enjoys reading but also writing.', 'She enjoys not only reading but also to writing.'], answer: 1,
    explanation: "With 'not only...but also', both halves should match grammatically: 'enjoys reading' / 'enjoys writing.'" },
  { id: 'e-h-9', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The critic's review was intentionally ___, offering praise and criticism in equal measure so as to avoid appearing biased toward either the studio or independent filmmakers.",
    choices: ['scathing', 'equivocal', 'effusive', 'derivative'], answer: 1,
    explanation: "'Equivocal' means deliberately ambiguous or noncommittal, matching the balance of praise and criticism described." },
  { id: 'e-h-10', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: "The collection of rare manuscripts, along with several first-edition novels, ___ housed in the university's special archive.",
    choices: ['are', 'is', 'were', 'have been'], answer: 1,
    explanation: "The subject is the singular 'collection'; the phrase 'along with several first-edition novels' does not change the verb's number, so 'is' is correct." },
  { id: 'e-h-11', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: 'A student wants to support the claim that urban green spaces improve mental health by citing a specific study. Which sentence best achieves this goal?',
    choices: ['Parks are nice places to relax.', 'A 2023 study found that residents living near urban parks reported 20% lower anxiety levels than those without such access.', 'Many cities are building more parks.', 'Green spaces have existed in cities for centuries.'], answer: 1,
    explanation: 'Only this option cites a specific, sourced statistic directly supporting the claim.' },
  { id: 'e-h-12', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: 'Passage: "Economists have long debated whether technological automation displaces workers permanently or merely shifts employment toward new sectors; historical precedent from the industrial revolution suggests the latter, yet critics argue that the speed and scope of contemporary automation may outpace the economy\'s historical capacity to generate replacement jobs." The passage suggests that critics of the historical-precedent argument believe:',
    choices: ['automation has never displaced workers in the past.', "the current pace of automation may exceed the economy's ability to adapt as it did historically.", 'new sectors will definitely absorb all displaced workers.', 'the industrial revolution created no new jobs.'], answer: 1,
    explanation: 'The passage states critics worry contemporary automation\'s "speed and scope" may "outpace the economy\'s historical capacity to generate replacement jobs."' },
  { id: 'e-h-13', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: 'Despite the mounting evidence against his theory, the researcher remained ___, refusing to consider any alternative explanation.',
    choices: ['ambivalent', 'intransigent', 'indifferent', 'receptive'], answer: 1,
    explanation: "'Intransigent' means stubbornly unwilling to change one's views, matching the refusal to consider alternatives." },
  { id: 'e-h-14', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: 'Which sentence corrects the comma splice?',
    choices: ['The experiment failed, the hypothesis was clearly flawed.', 'The experiment failed; the hypothesis was clearly flawed.', 'The experiment failed the hypothesis was clearly flawed.', 'The experiment, failed, the hypothesis was clearly flawed.'], answer: 1,
    explanation: 'A semicolon correctly joins two independent clauses without a coordinating conjunction.' },
  { id: 'e-h-15', subject: 'english', difficulty: 'hard', topic: 'Transitions',
    question: 'The new policy reduced emissions significantly; ___, it raised production costs for smaller manufacturers.',
    choices: ['consequently', 'nevertheless', 'for example', 'similarly'], answer: 1,
    explanation: "'Nevertheless' signals the concession between a positive effect (reduced emissions) and a negative one (higher costs)." },
  { id: 'e-h-16', subject: 'english', difficulty: 'hard', topic: 'Punctuation',
    question: 'Which sentence uses punctuation correctly?',
    choices: ['The committee reached a decision; approve the new budget.', 'The committee reached a decision: approve the new budget.', 'The committee reached a decision, approve the new budget.', 'The committee reached a decision - : approve the new budget.'], answer: 1,
    explanation: 'A colon correctly introduces an explanation or elaboration of the preceding independent clause.' },
  { id: 'e-h-17', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: 'Passage: "While proponents of standardized testing argue that it provides an objective, comparable measure of student achievement across diverse school systems, opponents contend that such tests often reflect socioeconomic advantages more than actual learning, since students from wealthier backgrounds typically have greater access to test preparation resources." According to the passage, opponents of standardized testing argue that test scores may primarily reflect:',
    choices: ["a student's natural intelligence.", 'the quality of a school\'s teaching alone.', 'socioeconomic advantages such as access to test preparation.', 'the difficulty of the test itself.'], answer: 2,
    explanation: 'The passage states opponents believe scores reflect "socioeconomic advantages more than actual learning," citing test-prep access specifically.' },
  { id: 'e-h-18', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The ambassador's remarks were carefully ___, conveying disapproval without ever using an accusatory tone.",
    choices: ['vitriolic', 'measured', 'incendiary', 'apathetic'], answer: 1,
    explanation: "'Measured' means carefully controlled and restrained, matching the deliberate, non-accusatory tone described." },
  { id: 'e-h-19', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: "The professor's argument was so ___ that it left no room for counterargument.",
    choices: ['tenuous', 'incontrovertible', 'superficial', 'ambiguous'], answer: 1,
    explanation: "'Incontrovertible' means impossible to deny or dispute, matching an argument that leaves no room for rebuttal." },
  { id: 'e-h-20', subject: 'english', difficulty: 'hard', topic: 'Grammar',
    question: 'Which sentence correctly uses the past perfect tense?',
    choices: ['By the time the guests arrived, she cooked the entire meal.', 'By the time the guests arrived, she had cooked the entire meal.', 'By the time the guests arrive, she had cooked the entire meal.', 'By the time the guests arrived, she has cooked the entire meal.'], answer: 1,
    explanation: "The past perfect 'had cooked' correctly shows an action completed before another past action ('arrived')." },
  { id: 'e-h-21', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: 'A writer wants to introduce a counterargument before refuting it. Which transition best serves this purpose?',
    choices: ['furthermore', 'critics might argue', 'similarly', 'in summary'], answer: 1,
    explanation: "'Critics might argue' explicitly signals an opposing view is being introduced, setting up a refutation." },
  { id: 'e-h-22', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: "Passage: \"The architect's design, initially derided as impractical and overly ambitious, has since become a defining feature of the city's skyline, prompting a reassessment of what constitutes practical urban design.\" The passage suggests that the architect's design ultimately:",
    choices: ['failed to gain any recognition.', 'challenged prevailing assumptions about practical design.', 'was quickly demolished due to impracticality.', 'had no lasting impact on the city.'], answer: 1,
    explanation: 'The design prompting a "reassessment of what constitutes practical urban design" shows it challenged existing assumptions.' },
  { id: 'e-h-23', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: 'The negotiations reached an ___ after both sides refused to compromise on key terms.',
    choices: ['consensus', 'impasse', 'agreement', 'resolution'], answer: 1,
    explanation: "'Impasse' means a deadlock where no progress can be made, matching both sides refusing to compromise." },
  { id: 'e-h-24', subject: 'english', difficulty: 'hard', topic: 'Modifiers',
    question: 'Which sentence is free of a misplaced modifier?',
    choices: ['Nearly finished, the team celebrated the completed project.', 'Nearly finished, the project was celebrated by the team.', 'The team celebrated the nearly finished project.', 'The project the team celebrated was nearly the finished.'], answer: 2,
    explanation: "Placing 'nearly finished' directly before 'project' avoids ambiguity about what was nearly finished." },
  { id: 'e-h-25', subject: 'english', difficulty: 'hard', topic: 'Rhetorical Synthesis',
    question: 'Which sentence best uses a specific example to support the claim that renewable energy is becoming more cost-competitive?',
    choices: ['Renewable energy is getting cheaper.', 'In many regions, solar power now costs less per kilowatt-hour than coal-generated electricity.', 'People are switching to renewable energy.', 'Renewable energy has many benefits.'], answer: 1,
    explanation: 'Only this option provides a specific, concrete cost comparison supporting the claim.' },
  { id: 'e-h-26', subject: 'english', difficulty: 'hard', topic: 'Reading Comprehension',
    question: "Passage: \"While early critics dismissed the study's sample size as too small to draw meaningful conclusions, subsequent replications with larger cohorts have consistently confirmed its central findings, lending the original research credibility it initially lacked.\" According to the passage, the original study's credibility was strengthened by:",
    choices: ['its large initial sample size.', 'later studies with larger sample sizes confirming its findings.', "the critics' initial support.", 'the researchers retracting their claims.'], answer: 1,
    explanation: 'The passage states that "subsequent replications with larger cohorts" confirmed the findings, lending credibility.' },
  { id: 'e-h-27', subject: 'english', difficulty: 'hard', topic: 'Vocabulary',
    question: 'Her ___ response to the criticism—calm, measured, and unemotional—surprised those who expected her to react defensively.',
    choices: ['vehement', 'equanimous', 'indignant', 'flustered'], answer: 1,
    explanation: "'Equanimous' means calm and composed, matching a response described as calm, measured, and unemotional." },
  { id: 'e-h-28', subject: 'english', difficulty: 'hard', topic: 'Parallelism',
    question: 'Which sentence correctly uses parallel structure in a list?',
    choices: ['The workshop covered writing skills, how to present, and management of time.', 'The workshop covered writing skills, presentation skills, and time management.', 'The workshop covered how to write, presenting, and time management.', 'The workshop covered writing, to present, and managing time.'], answer: 1,
    explanation: 'All three items should share the same noun-phrase form: writing skills, presentation skills, time management.' },
];
